Invalidate user environment on update
orchest/orchest pull request #100
Opened 2020-12-21 17:21 UTC by fruttasecca

This PR makes it so that user environments are invalidated when Orchest updates, to avoid issues related to mismatching versions of the `Orchest SDK` in different environments.

2020-12-21 17:30 UTC, ricklamers approved these changes

2020-12-22 10:58 UTC, yannickperrenet requested changes
Although in general I think the orchest-ctl could need some touch-ups, the new functions should in my opinion be defined in `utils.py`

Other than that a great addition!

2020-12-22 10:58 UTC, yannickperrenet commented on services/orchest-ctl/app/cmdline.py
> +def clear_environment_images():
I think this functions should be defined in `utils.py` instead.

2020-12-22 11:23 UTC, fruttasecca commented on services/orchest-ctl/app/cmdline.py
> +def clear_environment_images():
Indeed.

2020-12-22 11:45 UTC, yannickperrenet approved these changes

2020-12-22 11:53 UTC, merged