Add delete project to Project Settings
orchest/orchest pull request #1027
Opened 2022-06-07 08:53 UTC by BrunoOrchest

## Description

Description of what your PR solves or adds.

Fixes: #876

## Checklist

- [x] The documentation reflects the changes.
- [x] The PR branch is set up to merge into `dev` instead of `master`.
- [x] In case I changed one of the services’ `models.py` I have performed the appropriate database
      migrations (refer to `scripts/migration_manager.sh`).
- [x] In case I changed code in the `orchest-sdk` I followed its [release
      checklist](https://github.com/orchest/orchest/blob/master/orchest-sdk/python/RELEASE-CHECKLIST.md)
- [x] In case I changed code in the `orchest-cli` I followed its [release
      checklist](https://github.com/orchest/orchest/blob/master/orchest-cli/RELEASE-CHECKLIST.md)
- [x] I haven't introduced breaking changes that would disrupt existing jobs, i.e. backwards
      compatibility is maintained.
- [x] In case I changed the dependencies in any `requirements.in` I have run `pip-compile` to update
      the corresponding `requirements.txt`.

2022-06-07 09:14 UTC, iannbing commented on services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
> +    let deletePromise = makeRequest("DELETE", "/async/projects", {
I looked into the current implementation of deleting a project, and found two appearances:
- `deleteProject` in `ImportDialog`, using `fetcher`
- `deleteProjectRequest` in `ProjectsView`, using `makeRequest`

We are deprecating `makeRequest` and use `fetcher` instead.

```
import { fetcher } from "@orchest/lib-utils";

```

It'd be even better if we clean up a bit by moving `deleteProject` to a separate file and import it in `ImportDialog`,  `ProjectsView` and `ProjectSettingsView`.

2022-06-07 09:18 UTC, iannbing commented on services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
> +      <Modal open={isDeletingProject}>
Is there any reason you chose `Modal` over `Dialog`? Quote from [MUI](https://mui.com/material-ui/react-modal/)

> If you are creating a modal dialog, you probably want to use the [Dialog](https://mui.com/material-ui/react-dialog/) component rather than directly using Modal. Modal is a lower-level construct that is leveraged by the following components:

If we must create an exception here, it would be nice to leave a comment as a reference 🙂.

2022-06-08 12:33 UTC, ncspost commented
<img width="330" alt="CleanShot 2022-06-08 at 13 33 00@2x" src="https://user-images.githubusercontent.com/6852479/172617139-64cfa91d-e579-4591-9bec-3e1974620c40.png">
 
I'd even potentially hide this behind a dropdown to add a bit more friction

2022-06-08 12:46 UTC, BrunoOrchest commented
> <img alt="CleanShot 2022-06-08 at 13 26 00@2x" width="1289" src="https://user-images.githubusercontent.com/6852479/172615717-1b999b90-6dfb-475e-8067-d9638448d9b1.png">

This seems better but to implement, it would be part of the overall redesign of the page. Should we just try to find a quick solution for the button for now, and then focus on the re-design?

2022-06-08 12:57 UTC, ncspost commented
> This seems better but to implement, it would be part of the overall redesign of the page. Should we just try to find a quick solution for the button for now, and then focus on the re-design?

Sorry - forget to say ignore the other bits.

The only stuff that's in scope is what I listed above.

2022-06-09 09:15 UTC, BrunoOrchest commented
Adding a confirmation text field Ala Gitlab will be tricky without re-designing the warning dialog as it doesn't really support validation for the Confirm button (afaik). Will this be sufficient for now until the redesign @ncspost ?

<img width="624" alt="Screenshot 2022-06-09 at 10 15 30" src="https://user-images.githubusercontent.com/104759317/172811788-82a506c5-d48a-4c4e-89ca-7813eb8ad787.png">

2022-06-09 10:19 UTC, ncspost commented
That's fine @BrunoOrchest - let's update the copy and styles though...

- Heading: Delete [project name]?
- Body: "Warning: Deleting a Project is permanent. All associated Jobs and resources will be deleted and unrecoverable."
- Cancel button: Blue text
- Confirm: Change to Red filled button with "Delete Project" copy

2022-06-09 10:48 UTC, BrunoOrchest commented
> - Cancel button: Blue text
> - Confirm: Change to Red filled button with "Delete Project" copy

Changing these will change also the colours on other dialogs throughout. (We can make it specific for this only I think, but then it will be inconsistent with other dialogs we have throughout the app for other destructive and non-destructive actions)

2022-06-09 11:41 UTC, iannbing commented on services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
> +            p: 4,
I don't think this styling is working.

2022-06-09 11:43 UTC, iannbing commented on services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
> +      <Dialog open={isDeletingProject}>
This dialog is probably never rendered? `setIsDeletingProject(true);` is run in `finally`

2022-06-09 12:47 UTC, BrunoOrchest commented on services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
> +          }
Kept the same logic as in other place where this is set before resolving the promise. Changing.

2022-06-09 12:48 UTC, BrunoOrchest commented on services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
> +      <Dialog open={isDeletingProject}>
Refactoring error, it should be set to true before doing the call, and then to false in finally.

2022-06-09 13:03 UTC, iannbing commented on services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
> +            p: 4,
There are a few complementary components you could use with `Dialog`. See [MUI doc](https://mui.com/material-ui/react-dialog/#main-content) or check some implementation in our codebase, for example [SystemDialog](https://github.com/orchest/orchest/blob/master/services/orchest-webserver/client/src/components/SystemDialog.tsx).

<img width="281" alt="Screenshot 2022-06-09 at 15 00 40" src="https://user-images.githubusercontent.com/627607/172853037-61dd116a-6a3e-4dd2-8412-9896f63f9376.png">

2022-06-09 14:39 UTC, ncspost commented
Looks great! Just need to change copy of the `confirm` button to `Delete Project` please!

2022-06-09 16:27 UTC, iannbing commented on services/orchest-webserver/client/src/contexts/AppContext.tsx
> +  warning?: boolean;
Not sure if it's a good idea to add a workaround to a very generic implementation that is used across the whole app. In general, I would propose limiting a workaround within a component, and be more strict on things like `AppContext` and `SystemDialog`.

What about properly add a more usable property to `callbackOrParams`, for example: 

```

callbackOrParams?:
    | ConfirmHandler
    | {
        onConfirm: ConfirmHandler;
        onCancel?: CancelHandler;
        confirmLabel?: string;   // you can use this to change "DELETE" to "DELETE PROJECT"
        cancelLabel?: string;
        // extra property here, something like `confirmButtonColor`?
      }

```

If it's too much work for this specific task, implementing a Dialog directly in `ProjectSettingsView` could also be a good option imo. We can improve `setConfirm` later.

2022-06-09 16:32 UTC, iannbing commented on services/orchest-webserver/client/src/views/ProjectSettingsView.tsx
> +      async (resolve) => {
To specify Confirm button label, you could change the third arg an object `callbackOrParams`, see [useCheckUpdate](https://github.com/orchest/orchest/blob/7671975e58277ba104b6533955293e4e12acf86d/services/orchest-webserver/client/src/hooks/useCheckUpdate.tsx#L138) for example.

2022-06-20 13:47 UTC, yannickperrenet requested changes
Seems like there are still a few open comments on the PR, but other than that I think it looks good :+1:

2022-07-22 05:24 UTC, iannbing commented
@yannickperrenet @mausworks  This UX issue #876 would most likely be gone (or very trivial) in the new design. I'm not sure if it's still worth it to work on this PR.

2022-08-01 16:52 UTC, mausworks commented
Discussed this with @iannbing, I'm closing this PR as the settings-page redesign replaces this.

2022-08-01 16:52 UTC, closed without merging