Improve endpoints transactions
orchest/orchest pull request #111
Opened 2021-01-14 13:20 UTC by fruttasecca

This PR aims to improve the readability, testability, and error handling of the `orchest-webserver` and `orchest-api`.

A common theme throughout a lot of endpoints is to have effects on the database and collateral effects that affect the filesystem, the docker environment, the celery worker queue, a background scheduler, etc. When those two things are intertwined it makes for code that is harder to debug and that can be more prone to leave the state inconsistent in case of error.

For this reason, the PR introduces a `TwoPhaseExecutor` and a `TwoPhaseFunction` class, to be used in the aforementioned endpoints. Without delving into implementation details, the execution of requests that affect both the database and have collateral effects is separated into two phases, a transactional one, and a collateral one. So that issues during the first can leave the state unadulterated. See `lib/python/orchest-internals/_orchest/internals/two_phase_executor.py` for more details.

Moreover, the PR pulls up database commits to higher levels of the call stack, as suggested by the good practises of `sqlalchemy`, introduces rollbacks where necessary and partially refactors the `orchest-webserver`.

2021-01-14 17:05 UTC, yannickperrenet commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +# apply db changes during the collateral phase, and cannot do otherwise.
I would suggest using a module level docstring instead.

2021-01-14 17:11 UTC, yannickperrenet commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +                logging.error(f"Error during revert call {i}: {e}")
I think this would end up using the root logger, instead we would want something like
```python
import logging

logger = logging.getLogger(__name__)

# And then do logging like:
logger.error(...)
```

2021-01-14 17:29 UTC, yannickperrenet commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
I am a bit confused by this pattern. Can we make it into a decorator?

```python
def add_to_collateral_queue(func):
    def wrapper(*args, **kwargs):
        # Add to queue
        pass

        # This would then run the transaction
        return func(*args, **kwargs)
    return wrapper
```
Or is this not possible as we would not be apple to pass the `self.tpe` as an argument to the decorator?

2021-01-14 17:33 UTC, yannickperrenet commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
Should we make this an abstract method?

2021-01-14 17:41 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +        self.environment_build_uuid = environment_build_uuid
Just as a thought. Could the use of attributes on `self` backfire? Should we instead go with a `self.data = {}` that is defined in the `TwoPhaseFunction`?

Now every subclass of `TwoPhaseFunction` defines a different set of attributes. Generally speaking it is good practice to define all your attributes in the `__init__` function. Not sure whether that translates to this setting through.

2021-01-14 17:46 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +            return {"message": str(e)}, 500
This try block seems a bit of overkill as the exception is also caught and logged in by the `TwoPhaseExecutor`. Although I do understand the need for it to return a different message / status code based on failure.

2021-01-14 17:50 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +            ).delete()
Is this something that we can add to the `CreateInteractiveSession` class by adding another notion to the `TwoPhaseFunction`, a certain method that should be run "on-failure"? Or is this case too rare to handle so generally?

2021-01-14 17:53 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +            ).delete()
Indeed this should have been implemented by overriding `revert()` of the `TwoPhaseFunction` class.

2021-01-14 17:54 UTC, yannickperrenet requested changes
@fruttasecca, you are an absolute machine! Great, great work :+1: 

The structure this PR brings to the code is invaluable in my opinion, so I am very glad to have it. 

I just had some minor comments to start a discussion.

2021-01-15 09:13 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +            return {"message": str(e)}, 500
I think we can get away without further logging since the `TwoPhaseExecutor` will take care of that, but we need to have the try block there to catch the exception and have custom behaviour when there is a failure, unless we want to introduce more abstraction and functionality in the `TwoPhaseExecutor`.

2021-01-15 09:35 UTC, fruttasecca commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
I'll look into this.

2021-01-15 09:43 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +            return {"message": str(e)}, 500
I will leave it up to you. I would be fine with having to put the tpe context manager (always) in a try-except block.

2021-01-15 09:47 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        db.session.commit()
Could you add some information in the docstring of the `TwoPhaseFunction` stating whether or not one of its methods is allowed to commit? We want it to be consistent over the entire application I assume and otherwise have it clear that the commit can change on a case-by-case basis.

2021-01-15 09:48 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        db.session.commit()
Will do.

2021-01-15 10:32 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +            return {"message": str(e)}, 500
Then I will leave it this way (except for the unnecessary logging, which has been removed).

2021-01-15 11:26 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +context and calling 2phase_function.transaction(*args, **kwargs), while
Don't think `2phase_function` is a valid identifier. Maybe just `two_phase_function`

2021-01-15 11:27 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +happen after all transactional code has execute, and will take core of
will take care of*

2021-01-15 11:28 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +transaction method, while you are free to do so if you need to apply db
Perhaps `Note that you should not call commit inside the transaction method,`

2021-01-15 11:28 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +        self.environment_build_uuid = environment_build_uuid
>Just as a thought. Could the use of attributes on self backfire? Should we instead go with a self.data = {} that is defined in the TwoPhaseFunction?

Not sure about this, would make accessing data more verbose.

>Now every subclass of TwoPhaseFunction defines a different set of attributes. Generally speaking it is good practice to define all your attributes in the __init__ function. Not sure whether that translates to this setting through.

This is something I would not mind, although as you say it might not translate to this setting. It's what felt more natural when we were prototyping it. @ricklamers ?

2021-01-15 11:30 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +    during a collateral() or revert call(). All in all, this means that:
the parents should be after revert instead: `revert()`

2021-01-15 11:42 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +        self.environment_build_uuid = environment_build_uuid
Seems to me that self.data is more Pythonic (as all instance methods will be defined in the `__init__`). I prefer to have explicit data passing through `self.data` in case the collateral method depends on some of the data passed in the arguments of the `transaction(args, kwargs)`, instead of passing those arguments to the constructor of the class and having all of that available for both the `transaction()` and `collateral()`.

2021-01-15 11:47 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +class DeleteProjectBuilds(TwoPhaseFunction):
I'm a bit confused by `DeleteProjectBuilds`, wouldn't we not use a two phase executor if there is no collateral?

2021-01-15 11:53 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +    def transaction(self, project_uuid: str, pipeline_uuid: str):
Love the types!

2021-01-15 11:54 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +class DeletePipeline(TwoPhaseFunction):
Are you wrapping transaction only methods in a TwoPhaseFunction in order to cleanly compose them with other TwoPhaseFunctions that have them as a subroutine that _do_ have collateral effects?

2021-01-15 11:56 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +class DeleteProjectBuilds(TwoPhaseFunction):
This is because of nesting. `DeleteProjectBuilds` uses `DeleteProjectEnvironmentBuilds`, which is itself a `TwoPhaseFunction`. `DeleteProjectEnvironmentBuilds` makes use of `AbortEnvironmentBuild`, which is a `TwoPhaseFunction`, and needed to be because it has a collateral effect.  The alternative would be to make the first two into functions that receive a `tpe` as an argument, although I think this would be a change for the worse.

2021-01-15 11:58 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +class DeletePipeline(TwoPhaseFunction):
Yes, I found it preferable and easier to expand later in case a collateral effect would need to take place.

2021-01-15 11:58 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        pass
I think this pass is a leftover?

2021-01-15 12:00 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        pass
Indeed

2021-01-15 12:01 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        # depend on the existence of the object in the DB. Need to make
I think session needs to be fully shutdown in order to start a new one because we name Docker containers by the project/pipeline uuid. We might be able to _not_ do this which would make stopping sessions instantaneous to the user. Probably a TODO if we notice that refactor is worthwhile.

2021-01-15 12:04 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        # depend on the existence of the object in the DB. Need to make
It should be possible to rename a container, although it will for sure lead to more changes.

2021-01-15 12:04 UTC, ricklamers commented on services/orchest-webserver/app/app/core/pipelines.py
> +        # was deleted through the filesystrem by the user, so the file
Small typo: filesystem

2021-01-15 12:05 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +        self.environment_build_uuid = environment_build_uuid
I'll go with using `self.data` and leave the argument passing in `transaction`.

2021-01-15 12:09 UTC, ricklamers commented on services/orchest-webserver/app/app/core/pipelines.py
> +                self.do_collateral = True
I'm seeing this `self.do_collateral` pattern emerge. In the sense that during the transaction one could find out the collateral should not happen. If we were to raise an error the collateral would also not happen (along with bubbling up such that other collaterals part of the TwoPhaseExecutor will not run).

What do you think is preferred? Just not executing this particular collateral? In a way _this_ TwoPhaseFunction does not know in what TwoPhaseExecutor it will be used (by encapsulation). But you could argue that the transaction should raise an exception in the case this particular cannot proceed as intended (giving the callee the responsibility to appropriately handle that).

2021-01-15 12:09 UTC, ricklamers commented on services/orchest-webserver/app/app/core/pipelines.py
> +            self.pipeline_uuidd = file_pipeline_uuid
Typoe: `pipeline_uuidd` should probably be `pipeline_uuid`.

2021-01-15 12:18 UTC, fruttasecca commented on services/orchest-webserver/app/app/core/pipelines.py
> +                self.do_collateral = True
I think we should leave the semantics of what happens in the `transaction` and `collateral` functions to the implementor (excluding commits, ofc). It might be the case that the `transaction` needs to take place while the `collateral` does not need to, I would not consider that an error.

2021-01-15 12:23 UTC, ricklamers commented on services/orchest-webserver/app/app/core/pipelines.py
> +            self.pipeline_uuidd = file_pipeline_uuid
Oh the irony: a typo in my comment about a typoe!

2021-01-15 12:25 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
I don't prefer this because we'd require the class implementer to decorate a function to add to the collateral queue. Which I don't want to implementer to be concerned with (properly decorating a specific function).

2021-01-15 12:31 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
To make this less confusing we could add to the collateral queue in the class constructor. @fruttasecca would this work?

2021-01-15 12:34 UTC, fruttasecca commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
Then you might have cases where the order in which the `transaction` functions are called does not dictate the order in which the `collateral` ones are since it would depend on the constructor.

2021-01-15 12:38 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
I guess it's less natural to have the collateral ordering be determined by the class initialization order. It could work, but now that you phrase it like that I'm not sure that my proposal is an improvement. Transaction invocation = collateral order seems most natural to me.

2021-01-15 12:40 UTC, fruttasecca commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
Indeed. From the user POV it would make things more complex, imo.

2021-01-15 13:10 UTC, yannickperrenet commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +        raise NotImplementedError()
Yea indeed from the POV of the user it actually becomes more complex. Lets leave it the way it is now ;)

2021-01-15 13:21 UTC, yannickperrenet approved these changes

2021-01-15 16:40 UTC, yannickperrenet approved these changes

2021-01-15 16:41 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        if not project_uuid or not pipeline_uuid:
Maybe a comment about why they could be `None`?

2021-01-15 16:43 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        if not project_uuid or not pipeline_uuid:
Other than that, latest changes LGTM!

2021-01-15 16:56 UTC, ricklamers commented on services/orchest-webserver/app/app/core/pipelines.py
> +                self.do_collateral = True
As discussed, we'll swap `do_collateral` for passing arguments that can dictate which parts of the collateral function (if any) execute.

2021-01-15 16:57 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +        self.environment_build_uuid = environment_build_uuid
We decided to pass the data using `self.collateral_kwargs` to make it more explicit what data is being used by the `collateral` function and to avoid introducing new class attributes outside of the `__init__`.

2021-01-15 17:00 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +    def _transaction(self, *args, **kwargs):  # pylint: disable=E0202
We should be able to get rid of the `# pylint: disable=E0202`

2021-01-15 17:00 UTC, fruttasecca commented on lib/python/orchest-internals/_orchest/internals/two_phase_executor.py
> +    def _transaction(self, *args, **kwargs):  # pylint: disable=E0202
Indeed, will do

2021-01-15 17:44 UTC, merged