Feature job scheduler
orchest/orchest pull request #115
Opened 2021-01-21 17:10 UTC by fruttasecca

This PR brings a job scheduler into Orchest. When creating a job, the job can be scheduled to be run right now, at a given time, or recurringly through a cron string.

The scheduler will take care of running any job run that was missed while Orchest was not running. Meaning that if 10 runs of a recurring job were missed, 10 runs will be scheduled once Orchest is running.

2021-01-22 08:18 UTC, yannickperrenet commented on services/orchest-api/app/app/core/scheduler.py
> +job runs that were missed will be scheduled and run.
If I am not mistaken the celery beat scheduler does not have this behavior, instead if a task was scheduled to run every minute and Orchest is down for 10 minutes then it would only schedule it once.

We should decide what exactly the behavior is we want. For example: a job that does some ETL task, then it might not make sense scheduling the task in quick succession because that would end up doing the exact same work.

2021-01-22 08:20 UTC, yannickperrenet commented on services/orchest-api/app/app/core/scheduler.py
> +                    > Job.next_scheduled_time
Seems like a strange auto-formatting to me, not sure why black would do this...

2021-01-22 08:28 UTC, ricklamers commented on services/orchest-api/app/app/core/scheduler.py
> +job runs that were missed will be scheduled and run.
I had a quick discussion about this with Jacopo earlier.

My preference is that jobs do not get ‘lost’ if Orchest is not running. So if my cron jon runs every hour and Orchest is down for 5, I don’t think it should run once and be done with it. But perhaps my preferred default is not the commonly accepted one. I’m open to changing opinion on this.

2021-01-22 08:31 UTC, yannickperrenet commented on services/orchest-api/app/app/models.py
>      )
Does this mean that the parameters of a job should not be updated, making the job immutable? Or do we want to have mutable jobs?

The front-end reads the pipeline definitions (from the filesystem) to display the parameters of the job so this would still work in both cases. An argument against immutable jobs would be that you cannot create a job from another job (and thus changing the parameters on the same version of the pipeline is harder, although not impossible). An argument against mutable jobs is untraceability/inconsistency.

2021-01-22 08:36 UTC, yannickperrenet commented on services/orchest-api/app/config.py
> +    SCHEDULER_INTERVAL = 10
Could you add that the unit is seconds?

2021-01-22 08:42 UTC, ricklamers commented on services/orchest-api/app/app/models.py
>      )
The front-end reads the pipeline definition from the `snapshot` that is copied at job creation time. So mutability doesn't fit naturally with how we've structured and IMO is not preferred. The more you can manually change the less reliable the system becomes. The overhead of creating a new job if you want to use a different state of the project seems perfectly fine with me.

2021-01-22 08:56 UTC, fruttasecca commented on services/orchest-api/app/app/core/scheduler.py
> +job runs that were missed will be scheduled and run.
I don't have a strong opinion on this either, and it could be a setting of Orchest.

2021-01-22 08:56 UTC, fruttasecca commented on services/orchest-api/app/app/core/scheduler.py
> +                    > Job.next_scheduled_time
No idea, wil fix.

2021-01-22 08:59 UTC, fruttasecca commented on services/orchest-api/app/app/models.py
>      )
@yannickperrenet not sure I understand the question, but the highlighted code does not imply that the job is immutable, it's actually the opposite since you could update the parameters with new ones and the next time the job is scheduled the parameters will affect how many runs are launched and their parameters.

2021-01-22 08:59 UTC, fruttasecca commented on services/orchest-api/app/config.py
> +    SCHEDULER_INTERVAL = 10
Will do

2021-01-22 10:27 UTC, yannickperrenet commented on services/orchest-webserver/app/app/views/orchest_api.py
> +                        pipeline_def["steps"][step_uuid]["parameters"] = step_parameters
The nested for-loop does not actually change the `json_return`, does it? Anyways I am a bit confused what exactly is being modified here with the deepcopy and pointing to the `json_return`

2021-01-22 10:28 UTC, fruttasecca commented on services/orchest-webserver/app/app/views/orchest_api.py
> +                        pipeline_def["steps"][step_uuid]["parameters"] = step_parameters
I believe you were looking at an outdated version of the code, the for loop has been fixed.

2021-01-22 10:45 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +                return {"message": "Failed update operation."}, 500
What exactly are the possibilities for a job status? If a job is a cron-like scheduled job, then its status will always be `STARTED` unless aborted?

2021-01-22 10:46 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +            job = models.Job.query.filter_by(job_uuid=job_uuid).one()
Why is this block not contained in a tpe?

2021-01-22 10:48 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +                return {"message": "Failed update operation."}, 500
Job status can be any of `ABORTED, PENDING, STARTED, SUCCESS`. As you say, a cron-like job is either `STARTED` or `ABORTED`.

2021-01-22 10:50 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +            job = models.Job.query.filter_by(job_uuid=job_uuid).one()
Because the PUT request does not have any collateral effects, unless I am missing it.

2021-01-22 10:52 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jobs.py
>          status_update = request.get_json()
I think I am missing the general logic of the scheduling implementation, because this endpoint no longer seems to be updating the status of the pipeline run and instead changes the status of the job.

2021-01-22 10:55 UTC, yannickperrenet requested changes
I think we need some discussions around the general implementation before merging it.

2021-01-22 10:56 UTC, yannickperrenet commented on services/orchest-api/app/app/core/scheduler.py
> +job runs that were missed will be scheduled and run.
> My preference is that jobs do not get ‘lost’ if Orchest is not running.

I don't think this makes sense if all the jobs are running with the exact same set of parameters. They would essentially all return the same result and just use compute (and therefore possibly lagging other tasks down the chain).

2021-01-22 11:01 UTC, yannickperrenet commented on services/orchest-api/app/app/models.py
>      )
> but the highlighted code does not imply that the job is immutable

I fully agree, but when reviewing the code I wanted to put down my ideas on the subject before forgetting it whilst searching for the corresponding code that implements it.

> So mutability doesn't fit naturally with how we've structured and IMO is not preferred.

I agree on this point and would rather go with immutable jobs. This then also nicely introduces a concept around versioning and forking (which we can add later).

> The functionality to update a job parameters or its cron string is already there as a PUT endpoint, we can expose such functionality through the GUI or not.

Not sure whether I want to leave the endpoint there if we choose not to go with mutable jobs, since then we have dangling code. And since the `strategy_json` would have to be updated (like you said) the endpoint in and of itself would not work.

2021-01-22 11:02 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_jobs.py
>          status_update = request.get_json()
The logic of this endpoint is unchanged, imo. On [master](https://github.com/orchest/orchest/blob/master/services/orchest-api/app/app/apis/namespace_jobs.py#L136), a run PUTs its state through this endpoint, and the endpoint also updates the job accordingly [by changing  one of its attributes](https://github.com/orchest/orchest/blob/master/services/orchest-api/app/app/apis/namespace_jobs.py#L147). 

The difference is that instead of using `completed_pipeline_runs` we are querying the db and based on that we decide if the job is completed or not, instead of updating `completed_pipeline_runs`, the end point is updating `status`.

2021-01-22 11:04 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +                return {"message": "Failed update operation."}, 500
Should we maintain a document or whatever to write this down? Possibly putting it in the development section somewhere in the [implementation details docs](https://orchest.readthedocs.io/en/latest/developer_guide/implementation_details.html)?

2021-01-22 11:05 UTC, fruttasecca commented on services/orchest-api/app/app/models.py
>      )
The endpoint would actually still work for updating the cron string of a recurrent job without additional webserver work involved I believe. We can simply delete the end point if we do not make use of it, of course.

2021-01-22 11:05 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +            job = models.Job.query.filter_by(job_uuid=job_uuid).one()
I recall a similar scenario (but I can definitely be mistaken) where there was also no collateral effect, yet it was still wrapped in a tpe for consistency and future extensibility. If not, then I am fine leaving it this way.

2021-01-22 11:09 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +            job = models.Job.query.filter_by(job_uuid=job_uuid).one()
Could it be that the reason was that the request was actualling making use of a `TwoPhaseFunction`, although it did not have any collateral effect itself? (but the 2pf did/could).

2021-01-22 11:11 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +                return {"message": "Failed update operation."}, 500
I think I'll go ahead and write a comment on top of the column declaration in `models`, we can then further extend the docs if we decide to do so.

2021-01-22 11:13 UTC, fruttasecca commented on services/orchest-api/app/app/core/scheduler.py
> +job runs that were missed will be scheduled and run.
I agree with @yannickperrenet. We have also to keep in mind that we are not providing a workflow management tool, so jobs getting lost while Orchest is offline could be part of the contract.

2021-01-22 12:24 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jobs.py
> +            job = models.Job.query.filter_by(job_uuid=job_uuid).one()
I am unsure and since you are more familiar then I am, its probably best to go with your judgement here :)

2021-01-22 12:27 UTC, yannickperrenet commented on services/orchest-api/app/app/models.py
>      )
Since the option of having mutable jobs is more or less implemented already and offers the users more flexibility, we decided to go with mutable jobs instead of immutable jobs. This might change in the future if the flexibility is restored in other way (possibly integrated versioning of projects) and going with immutable jobs for reliability.

2021-01-22 12:29 UTC, yannickperrenet commented on services/orchest-webserver/app/app/views/orchest_api.py
> +                        pipeline_def["steps"][step_uuid]["parameters"] = step_parameters
> I believe you were looking at an outdated version of the code

Indeed I was.

2021-01-22 18:41 UTC, ricklamers commented
I'll do some testing over the weekend, but I think most of it should be ready now.

Specifically I want to review whether we want to move the orchest-webserver `Job` state fully to the `orchest-api`. If the required refactoring is minimal I think I want to do it in this PR. We'll review that bit on Monday.

Great work everyone!

2021-01-26 09:14 UTC, yannickperrenet commented
After playing around a bit with the application I think this is a job well done! I do have some pointers though:

* After creating and starting a job, you can open that job to see its pipeline runs. However, the _ID_ column is no longer populated.
* I find _Creation status_ in the job list (so after clicking _Jobs_ in the left pane menu) somewhat confusing/useless as it only shows _Submitted_ or _Draft_, whilst I would argue that the _Job status_ you see when opening the job is what you actually want to see in the job list. Otherwise a user will have to click on all the jobs in order to find one that is still running. When adding the status in the job list, the status should also become searchable (isn't that right @ricklamers?) which I consider a value add.
* The job list is now ordered based on _Date created_ with the most recent date at the bottom, I would like to see that being reversed.

2021-01-26 18:58 UTC, yannickperrenet commented
I think we should add the the _refresh_ functionality from the pipeline runs list (after clicking on a job) to the job list as well. Otherwise you need to navigate away and back to see the job itself changing.

2021-01-28 11:55 UTC, yannickperrenet commented
> I think we should add the the refresh functionality from the pipeline runs list (after clicking on a job) to the job list as well. 

This is actually more in-line with how the projects and pipelines view work. And so we decided not to add this refresh button.

> Otherwise you need to navigate away and back to see the job itself changing.

You can just click on the "Jobs" in the left-pane menu, which is also just one click like the refresh button would have been.

2021-01-28 14:49 UTC, yannickperrenet approved these changes

2021-01-28 21:12 UTC, merged