Use ctr to download images even in docker env
orchest/orchest pull request #1150
Opened 2022-07-25 04:14 UTC by nhaghighat

## Description

TODO:

Fixes: #issue

## Checklist

- [ ] I have manually tested my changes and I am happy with the result.
- [ ] The documentation reflects the changes.
- [ ] The PR branch is set up to merge into `dev` instead of `master`.

2022-07-25 14:24 UTC, yannickperrenet commented on utility-containers/image-puller/pull_image.sh
> +    rm -rf pulled-image.tar && ctr -a=/var/run/containerd.sock i rm "${IMAGE_TO_PULL}"
Versus the existing 
```sh
    docker -H unix:///var/run/runtime.sock pull "${IMAGE_TO_PULL}" --disable-content-trust
```

these changes seem like they would incur significant overhead when running the `initContainer`, wouldn't they?

2022-07-25 15:18 UTC, nhaghighat commented on utility-containers/image-puller/pull_image.sh
> +    rm -rf pulled-image.tar && ctr -a=/var/run/containerd.sock i rm "${IMAGE_TO_PULL}"
They do, but only for the first time, because after that we check for the image existence,

2022-07-25 18:04 UTC, yannickperrenet commented on utility-containers/image-puller/pull_image.sh
> +    rm -rf pulled-image.tar && ctr -a=/var/run/containerd.sock i rm "${IMAGE_TO_PULL}"
> They do, but only for the first time

We would be hitting this case more often than you would initially think. Every time an Environment is build, this case is hit because it constitutes for a new image (i.e. `IMAGE_TO_PULL` here).

So I did a quick test (which ran on EKS with these changes):
1. Run the quickstart pipeline (`get-data.py` ran in `8s` as it wasn't the first time I ran the pipeline)
2. Rebuild the Environment with `echo "hi"` added to the setup script to ensure it would create a new image
3. Rerun the quickstart pipeline (`get-data.py` ran in `43s`)

That means the code we are discussing here has an overhead of `35s` in this case, which is not acceptable imo. We will be focusing on performance improvements in the next weeks anyways so we might as well make the change in this PR is performant.

2022-07-25 18:05 UTC, yannickperrenet requested changes
As per https://github.com/orchest/orchest/pull/1150#discussion_r929159246, I don't think the performance hit is acceptable and should be fixed before we can merge.

Great find though and great that you could pick this up so quickly :muscle: 

(cc @ricklamers @fruttasecca )

2022-07-25 18:12 UTC, nhaghighat commented
@yannickperrenet : fixing the performance hit requires a significant amount of work, if we want to postpone this, then our EKS users cant use orchest for a good amount of time.

2022-07-25 18:23 UTC, yannickperrenet commented on utility-containers/image-puller/pull_image.sh
> +    rm -rf pulled-image.tar && ctr -a=/var/run/containerd.sock i rm "${IMAGE_TO_PULL}"
And we would have to check whether kernels can timeout when taking such a long time to start.

2022-07-29 15:44 UTC, ricklamers commented
Not using this in favor of `buildah` in #1157

2022-07-29 15:44 UTC, closed without merging