Add OpenReplay to Orchest Cloud
orchest/orchest pull request #1170
Opened 2022-08-03 15:42 UTC by ricklamers

## Description
This adds OpenReplay to Orchest Cloud users, with all privacy preserving settings enabled.

## Checklist

- [x] I have manually tested my changes and I am happy with the result.
- [x] The documentation reflects the changes.
- [x] The PR branch is set up to merge into `dev` instead of `master`.
- [x] I haven't introduced breaking changes that would disrupt existing jobs, i.e. backwards compatibility is maintained.

2022-08-03 15:47 UTC, mausworks commented on services/orchest-webserver/app/app/config.py
> +    OPENREPLAY_INGEST_POINT = "https://openreplay.orchest.io"
I'm unsure of how our config is set up. Will this only be applied to cloud instances?

2022-08-03 15:50 UTC, mausworks commented on services/orchest-webserver/client/src/App.tsx
> +      // Initialize OpenReplay
Please remove this comment. I think the code is pretty self-descriptive. If you feel like extra detail is required, move this functionality to a function named `initializeOpenReplay`.

We just added a section in the [style guide Draft](https://www.notion.so/TypeScript-React-Conventions-Style-Guide-dc3172bc20c04da7900c6481e05525c3#586e5647ebbe4771909c387012f40392) about how we want comments to be used in the front-end. :+1:

2022-08-03 15:51 UTC, mausworks reviewed
LGTM, except for the nit about the comment. :+1:

2022-08-03 16:16 UTC, ricklamers commented on services/orchest-webserver/client/src/App.tsx
> +      // Initialize OpenReplay
Haha agree

2022-08-04 09:36 UTC, ricklamers commented on services/orchest-webserver/app/app/config.py
> +    OPENREPLAY_INGEST_POINT = "https://openreplay.orchest.io"
>I'm unsure of how our config is set up. Will this only be applied to cloud instances?

Yes.

2022-08-04 10:00 UTC, mausworks approved these changes

2022-08-04 11:58 UTC, mausworks requested changes
I think it's best we just go with the inline CSS solution. 🙂

2022-08-04 11:58 UTC, mausworks commented on services/orchest-webserver/client/public/index.html
> +    {{CSS_BLOCK}}
What do you think of doing this instead? `<style>{{CSS_CODE}}</style>`

That way you don't have to include the HTML in the CSS. :+1:

2022-08-04 11:58 UTC, mausworks commented on lib/javascript/build-frontend.sh
> +  if [ $3 == "inject-css" ]; then
I don't think that we should support both inline CSS _and_ CSS via `<link>`, I think it's better if we pick just one strategy, and stick to it. Less work to support both, and a cleaner implementation.

2022-08-04 14:13 UTC, ricklamers commented on lib/javascript/build-frontend.sh
> +  if [ $3 == "inject-css" ]; then
The reason we have it like this is for the development reload loop. `esbuild`/`sass` build with watch supports writing to the file. I didn't want to implement a custom watch loop.

2022-08-04 14:13 UTC, ricklamers commented on services/orchest-webserver/client/public/index.html
> +    {{CSS_BLOCK}}
See other comment.

2022-08-04 14:45 UTC, mausworks commented on lib/javascript/build-frontend.sh
> +  if [ $3 == "inject-css" ]; then
Gotcha, didn't think of that. It makes sense. :+1: 

Let's hope we can move away from SASS entirely soon.

2022-08-04 14:45 UTC, mausworks approved these changes

2022-08-04 16:15 UTC, iannbing approved these changes

2022-08-05 08:57 UTC, merged