Feature pipeline parameters
orchest/orchest pull request #134
Opened 2021-01-29 17:11 UTC by fruttasecca

This PR adds the concept of pipeline parameters. Pipeline parameters can be set up through the pipeline settings view when in the pipeline editor; moreover, pipeline parameters can be overridden for jobs.

- [x] The documentation reflects the changes.
- [x] I have manually tested the application to make sure the changes don’t cause any downstream issues.
- [x] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

2021-01-29 17:47 UTC, yannickperrenet commented
Resolves #125

2021-02-01 16:23 UTC, yannickperrenet commented on orchest-sdk/python/orchest/parameters.py
> +) -> None:
Didn't we want to add a warning as updating `pipeline_params` could introduce a race condition unaware to the user?

2021-02-01 16:28 UTC, yannickperrenet requested changes
I think we should add a warning somehow. Probably using the docstring:
```python
"""...
Warning:
    The warning message
"""
```
This will then also get rendered in the documentation as a warning using sphinx.

2021-02-01 16:42 UTC, fruttasecca commented on orchest-sdk/python/orchest/parameters.py
> +) -> None:
Will  do

2021-02-01 16:49 UTC, yannickperrenet commented
When configuring the parameters of the job, you see something like:
```
Pipeline: pipe
    a:[5]
step-name
    b:[6]
```
but I am not sure whether this is clear enough to the user. The confusion to me is mostly introduced by the fact that in the top it already states:
```
Pipeline
pipe
```

Happy to hear your thoughts as maybe I am just imaging the confusion :)

2021-02-01 18:28 UTC, yannickperrenet approved these changes

2021-02-02 11:16 UTC, merged