Feature debug dump
orchest/orchest pull request #147
Opened 2021-02-10 10:30 UTC by fruttasecca

This PR introduces a new CLI command, `debug`. The command will produce a dump of the logs and other information related to Orchest services. This will help in the debugging process since a user will have to run fewer commands to provide information.

The command also provides an `--ext` option, which outputs more extensive debug information. Note that some user data might be involuntarily included, depending on the circumstances, e.g. depending on the current state of Orchest and/or one of its services. Moreover, note that when running Orchest in `dev` mode some user data might also leak depending on the current state.

Content of the dump:
- Orchest config file
- Version of Orchest images
- Currently running Orchest containers
- Logs of Orchest containers
- Result of health checks 
-  Database schemas and other metadata
- Celery worker logs and the output of different `celery inspect` commands.

### Checklist
- [ ] The documentation reflects the changes.
- [X] I have manually tested the application to make sure the changes don’t cause any downstream issues.
- [X] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

2021-02-10 18:53 UTC, yannickperrenet commented
> The command also provides an --ext option, which outputs more extensive debug information. Note that some user data might be involuntarily included, depending on the circumstances, e.g. depending on the current state of Orchest and/or one of its services. Moreover, note that when running Orchest in dev mode some user data might also leak depending on the current state.

The "involuntarily" and "data might also leak" I do not like. Is this only present when the `--ext` flag is given? If so, then I would rather just say that the `--ext` could include data and so should only be used by users who are okay with this and drop the "involuntarily" as this sounds as if the software was designed incorrectly.

2021-02-10 18:57 UTC, yannickperrenet commented on services/orchest-ctl/app/cli/main.py
> +    Get Orchest version.
This probably got copied along from the version.

```suggestion
    Get status of Orchest.
```

2021-02-10 19:13 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +from app.orchest_resource_manager import OrchestResourceManager
I think putting both the `DockerWrapper` and `OrchestResourceManager` into their own module is a bit overkill. Mostly because the resource manager is just another layer of abstraction on top of the `DockerWrapper` (at least in its current state).

2021-02-10 19:14 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +    # Works locally, doesn't work here.
I do not understand this comment.

2021-02-10 19:14 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +    # Works locally, doesn't work here.
I guess its about the `nginx-proxy` line below? It should probably just be removed if it does not work.

2021-02-10 19:16 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +    ) = OrchestResourceManager().get_containers(state="running")
Feels a bit like a code smell to create a `DockerWrapper` and `OrchestResourceManager` for every function in this module. Mostly because the functions in this module are all called from one parent function, so why have every function create its own instance of the class?

2021-02-10 19:17 UTC, fruttasecca commented on services/orchest-ctl/app/debug.py
> +    # Works locally, doesn't work here.
You guessed right, will remove.

2021-02-10 19:18 UTC, fruttasecca commented on services/orchest-ctl/app/debug.py
> +from app.orchest_resource_manager import OrchestResourceManager
I'll put both of them in a single module, cannot put them in `orchest.py` because it will lead to circular imports AFAIK.

2021-02-10 19:20 UTC, fruttasecca commented on services/orchest-ctl/app/debug.py
> +    ) = OrchestResourceManager().get_containers(state="running")
We can have the parent function create 1 single instance and that's it, I went with making them as independent as possible but I have no problem with changing it.

2021-02-10 19:23 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +    ) = OrchestResourceManager().get_containers(state="running")
Why is the health check only run on running containers? I do get it partially, but shouldn't we make sure the health check passes (i.e. just getting the output) when Orchest is fully running? What if the user already stopped Orchest?

2021-02-10 19:28 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +            return
Now that I am also seeing this part, shouldn't we make it clear to the user that Orchest has to be running before running the debug command?

We could just give them a help message. Possibly even detecting whether Orchest is running and displaying the message based on the state. "Please make sure to start Orchest first", or something like this (see `OrchestApp.status` for an example).

2021-02-10 19:31 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +                "has never been run or it was removed when stopping Orchest."
I think we should keep in mind here that these messages might not make sense to the user. For example: "it was removed when stopping Orchest." makes a lot of sense to us, but I would argue that it does not have to make sense to a user.

2021-02-10 19:32 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +        del config["TELEMETRY_UUID"]
Nice catch ;)

2021-02-10 19:34 UTC, fruttasecca commented on services/orchest-ctl/app/debug.py
> +    ) = OrchestResourceManager().get_containers(state="running")
Not sure if I understand the question, but the health check is run only on running containers, so  if Orchest is not running it will not report any health issues , as expected, imo.

2021-02-10 19:38 UTC, yannickperrenet commented on services/orchest-ctl/app/docker_wrapper.py
> +    def copy_files_from_containers(self, files: List[Tuple[str, str, str]]):
Should have the `-> None` to indicate it does not actually return the files.

2021-02-10 19:38 UTC, fruttasecca commented on services/orchest-ctl/app/debug.py
> +            return
>Now that I am also seeing this part, shouldn't we make it clear to the user that Orchest has to be running before running the debug command?

I think that we can make it clearer that running the debug command while Orchest is running will give you more information, but Orchest does not have to be running for the debug command to go through. And it should not be a requirement imo. The command might be used in unforeseen cases where Orchest is not able to run, completely and/or partially.

2021-02-10 19:38 UTC, yannickperrenet commented on services/orchest-ctl/app/docker_wrapper.py
> +            path in the fs (to copy to).
Why instead not just receive three different args or kwargs? It would be a lot clearer than taking a tuple.

2021-02-10 19:38 UTC, fruttasecca commented on services/orchest-ctl/app/debug.py
> +                "has never been run or it was removed when stopping Orchest."
Agree

2021-02-10 19:40 UTC, yannickperrenet commented on services/orchest-ctl/app/docker_wrapper.py
> +        tar_file.close()
How long does this section take? Otherwise we could make this async as well. But I don't think we should bother if its quick anyways.

2021-02-10 19:40 UTC, fruttasecca commented on services/orchest-ctl/app/docker_wrapper.py
> +            path in the fs (to copy to).
Mostly because it would make the fact that those 3 pieces of info (id, from ,to) are related more explicit.

2021-02-10 19:41 UTC, fruttasecca commented on services/orchest-ctl/app/docker_wrapper.py
> +        tar_file.close()
Takes pretty much no time, the bottleneces are `celery inspect` command and getting container versions.

2021-02-10 19:41 UTC, yannickperrenet commented on services/orchest-ctl/app/utils.py
> +        time.sleep(0.25)
Now that the `time.sleep` is updated the comment should probably be `8` instead of `4` now. But it would just become a guess at this point and so going with `10` is also completely fine with me.

2021-02-10 19:45 UTC, yannickperrenet requested changes
The dump includes the right information I would say, so good job on that.

I do think we should communicate better to the user that Orchest has to be running before executing the debug command.

2021-02-11 11:11 UTC, yannickperrenet commented on services/orchest-ctl/app/docker_wrapper.py
> +            path in the fs (to copy to).
I prefer going with args/kwargs over the tuple, but since its just a matter of opinion I am fine either way.

2021-02-11 11:15 UTC, yannickperrenet commented on services/orchest-ctl/app/docker_wrapper.py
> +            path in the fs (to copy to).
On another note, the indentation of the docstring has to be like (not sure about the linewrapping here since that is hard to check in a GitHub comment):
```python
"""
            files: A list of triples where, for each triple, the first
                element is the container id, the second element is a path
                in the container (to copy from) and the third element is a
                path in the fs (to copy to).
"""
```
You can refer to: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html if things are unclear about docstring formatting.

2021-02-11 11:16 UTC, fruttasecca commented on services/orchest-ctl/app/docker_wrapper.py
> +            path in the fs (to copy to).
I'll then opt to leave it as it is to save some time.

2021-02-11 12:54 UTC, yannickperrenet commented on services/orchest-ctl/app/debug.py
> +                    "data will be incomplete."
Should comments like these not be in the debug dump instead of outputting them to the user? The user might read this and think "oh the debug command is not working correctly". 

Another option could be to go use the logging module, which will then be outputted if the debug command is run with the `-vvv` option (depending on the log level of course).

Lastly, the `utils.echo` function should probably be changed to do the line wrapping by default (since all output should be consistent). Now it needs to be passed which is just unnecessary. Do you know what I mean or do you want me to fix it?

2021-02-11 13:02 UTC, fruttasecca commented on services/orchest-ctl/app/debug.py
> +                    "data will be incomplete."
>Should comments like these not be in the debug dump instead of outputting them to the user? The user might read this and think "oh the debug command is not working correctly".

>Another option could be to go use the logging module, which will then be outputted if the debug command is run with the -vvv option (depending on the log level of course).

I think using the logger for this kind of message is probably for the best.

>Lastly, the utils.echo function should probably be changed to do the line wrapping by default (since all output should be consistent). Now it needs to be passed which is just unnecessary. Do you know what I mean or do you want me to fix it?

I'll do that.

2021-02-11 13:26 UTC, yannickperrenet approved these changes

2021-02-11 13:27 UTC, merged