Feature jupyterlab pipeline editor swap
orchest/orchest pull request #151
Opened 2021-02-15 14:12 UTC by ricklamers

This PR changes the default view someone sees when opening a pipeline. Instead of landing directly in the pipeline editor we open the JupyterLab editor to allow people to more closely follow their existing workflow, and transition to constructing the pipeline after they have created their initial notebooks/scripts.

- [x] The documentation reflects the changes.
- [x] I have manually tested the application to make sure the changes don’t cause any downstream issues.
- [x] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

This PR branch extends `feature-url-routing` as these features were loosely coupled in their implementation.

2021-02-16 11:48 UTC, yannickperrenet commented
Before I start reviewing the code, I want to say that I think the swap makes a lot of sense especially for new users. Additionally, the URL routing is terrific as well, this is a huge quality of life improvement in my opinion.

Great work!

2021-02-16 11:55 UTC, yannickperrenet commented on services/orchest-webserver/app/app/core/projects.py
> +        expected_git_dir = os.path.join(full_project_path, ".git")
I think this assumption works in 99.9% (but might also be my lack of git knowledge) of the cases, especially when it comes to git repositories as projects inside Orchest. So looks good to me.

2021-02-16 12:01 UTC, yannickperrenet commented on services/orchest-webserver/app/static/js/src/components/PipelineList.js
> +      props.queryArgs.read_only = "true";
@ricklamers The parsing to strings here is for consistency in the query string (of the URL), like you mentioned the other day. Am I right?

2021-02-16 12:09 UTC, yannickperrenet requested changes
Even though everything looks good, I think it makes sense to hold off a little with merging to make sure we have enough time for testing due to the sheer number of minor changes across all the different views.

2021-02-16 12:46 UTC, fruttasecca commented
Looks like there are a couple of issues when adding new users. Adding multiple users and then trying to go backward in the page means having to go back 1 time for each user that was added. Moreover, some previous state is still visible (see the picture).
![image](https://user-images.githubusercontent.com/19429509/108064531-1d40fd80-705d-11eb-8ccb-205630191ffb.png)

Moreover, adding the same user multiple times correctly leads to an error, although the error does not seem to have been managed properly, since it leads to a blank view.

2021-02-16 12:52 UTC, fruttasecca commented
Routing does not always set the pane selection properly. For example, select `Projects` and go to the project settings. Then click on any link (pipeline, job, environment). You will be brought to the correct view and the correct pane will be selected, but going back does not select `Projects` again.

2021-02-16 12:55 UTC, yannickperrenet commented
Now that we have URL routing I figured I try to use Orchest using multiple tabs. Then I noticed, over all open tabs only one JupyterLab iframe will load. 

Is this intended? And if so, is this purely browser based meaning that using the same instance with multiple users does not run into the same issue?

2021-02-16 13:00 UTC, fruttasecca commented
Routing does not currently allow to move forward in the file manager when coming from another view. E.g. it's possible to select any pane but the file manager, the select the file manager and navigate through the file system. It is then possible to go backwards up to the views that was initially selected, while going forward will stop at the "root" of the file manager view. It's probably related to the file manager itself, just mentioning in case it is not.

2021-02-16 13:03 UTC, ricklamers commented on services/orchest-webserver/app/static/js/src/components/PipelineList.js
> +      props.queryArgs.read_only = "true";
That's correct! All queryArgs should be strings.

2021-02-16 13:58 UTC, ricklamers commented
> Routing does not currently allow to move forward in the file manager when coming from another view. E.g. it's possible to select any pane but the file manager, the select the file manager and navigate through the file system. It is then possible to go backwards up to the views that was initially selected, while going forward will stop at the "root" of the file manager view. It's probably related to the file manager itself, just mentioning in case it is not.

Deeper routing for the file manager is currently not implemented by choice. It's not clear whether we're sticking to it long term, so further effort for deeper integration is not something we're prioritizing now.

> Now that we have URL routing I figured I try to use Orchest using multiple tabs. Then I noticed, over all open tabs only one JupyterLab iframe will load.
> Is this intended? And if so, is this purely browser based meaning that using the same instance with multiple users does not run into the same issue?

JupyterLab should work in multiple tabs (multiple instances). Turns out Jupyter automatically forces you to use different workspaces if you open the same JupyterLab instance in multiple tabs. This behavior was broken because `pushState` calls were overriden (which was a fix to not introduce no-op history pushes JupyterLab redirects created as an iframe). It looks like we can either give up allowing JupyterLab to be open in multiple tabs _or_ clean back/forward history (no no-op entries). I'm voting to go for giving up the latter, thus supporting having open multiple JupyterLab pages in a single browser. This is because other side effects of disabling in `pushState` are difficult to predict.

> Routing does not always set the pane selection properly. For example, select Projects and go to the project settings. Then click on any link (pipeline, job, environment). You will be brought to the correct view and the correct pane will be selected, but going back does not select Projects again.

With explicit view relations (parent -> child) defined this should now be fixed.

> Looks like there are a couple of issues when adding new users. Adding multiple users and then trying to go backward in the page means having to go back 1 time for each user that was added. Moreover, some previous state is still visible (see the picture).

This is default browser navigation behavior for <form> interactions (POST submit requests). So we'll leave this as is.

>Moreover, adding the same user multiple times correctly leads to an error, although the error does not seem to have been managed properly, since it leads to a blank view.

Added server side validation and client side warnings for this.

2021-02-16 14:21 UTC, ricklamers commented on services/orchest-webserver/app/app/core/projects.py
> +        expected_git_dir = os.path.join(full_project_path, ".git")
https://git-scm.com/docs/gitrepository-layout

I think we're good according to this. It's either a `.git` folder or file. 'bare' git repositories are not supported (as directories in `projects/`).

2021-02-19 16:36 UTC, yannickperrenet commented on services/orchest-api/app/app/utils.py
> +    print("exp", len(exps))
I guess these `print` statements will be removed later on or be turned into logging calls?

2021-02-19 17:28 UTC, merged