Feature JupyterLab server extensions
orchest/orchest pull request #163
Opened 2021-03-07 18:09 UTC by ricklamers

This PR adds JupyterLab server extensions using an image build mechanism similar to environments.

### Checklist

- [ ] The documentation reflects the changes.
- [x] I have manually tested the application to make sure the changes don’t cause any downstream issues.
- [x] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

2021-03-08 09:14 UTC, yannickperrenet commented on services/jupyter-server/start.sh
> +cp -rnT "$build_path/extensions" "$userdir_path/extensions"
Why is this moved upwards? This will always do the copy even if it is unnecessary.

2021-03-08 09:26 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/__init__.py
> +api.add_namespace(ns_jupyter_builds)
Could you make it such that these namespaces are alphabetically sorted (just like the imports).

2021-03-08 09:30 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        ).first()
Would it make sense to make this "gate check" to the `namespace_validations.py`? To make sure the orchest-api doesn't call its own API, the logic can be put in a module level function.

2021-03-08 09:33 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +            raise Exception("JupyterLab build in progress. Cannot start session.")
I think we should have a custom error (probably best defined in the internal library) to trigger the TwoPhaseExecutor. Something like: `TriggerTPEError`. This is way more explicit than it is currently.

@fruttasecca What do you think?

2021-03-08 09:37 UTC, yannickperrenet commented on services/orchest-api/app/app/schema.py
> +        ),
Could you add `required=True` where necessary, if applicable and otherwise explicitly state `required=False`.

2021-03-08 09:55 UTC, yannickperrenet commented on services/orchest-api/app/app/core/sessions.py
> +        )
Why does the format need the `orchest_version`? I guess it is so that the up-to-date build is used when running Orchest.

Can't we then just make use of the `:latest` tag to ensure the latest build (user-configured) jupyterlab is used? I think this is cleaner from a Docker perspective. 

Please let me know if I am missing something.

2021-03-08 10:01 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jupyter_builds.py
> +    pass
Should be in a `error.py` module. Similar to `orchest-sdk/python/orchest/error.py` and `services/orchest-ctl/app/error.py` (you can refer to the [Python docs on user defined exceptions](https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions).

2021-03-08 10:04 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jupyter_builds.py
> +        if jupyter_build:
We need to specifically check for `None` here, so it should be
```python
if jupyter_build is not None:
```

2021-03-08 10:05 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jupyter_builds.py
> +
The lines can be removed.

2021-03-08 10:10 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_jupyter_builds.py
> +            AbortJupyterBuild(self.tpe).transaction(build.uuid)
Does this mean that if you click the `BUILD` button, before the previous build is finished, that the previous build will be aborted? Should this not give a warning to the user instead, e.g.: "Cannot build, a build is already running".

Similarly, we also do not shut down sessions if they are in progress.

2021-03-08 10:18 UTC, yannickperrenet requested changes
Great work! This should wrap up persisting user configurations for JupyterLab (see #131).

When it comes to the documentation, what do you think about putting it in [Other](https://orchest.readthedocs.io/en/latest/user_guide/other.html), or do we want to have a complete section about IDE configurations? It is quite the feature I think.

To me the most important questions regarding this PR are:

* Using `:latest` only instead of also using the Orchest version for the names of the Docker images (for jupyter builds).
* Should the user not be warned when building without the previous build being finished?

2021-03-08 10:19 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +            raise Exception("JupyterLab build in progress. Cannot start session.")
I am not really sure what the use case would be. Would the TwoPhaseExecutor act differently based on an exception being or not being a `TriggerTPEError`?

2021-03-08 11:48 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +            raise Exception("JupyterLab build in progress. Cannot start session.")
The TPE would not act differently, but raising a generic `Exception` is a bit vague to me. When raising a `TriggerTPEError` (or another name) then at least it is clear that the exception is specifically raised to trigger the TPE.

The fact this it is an `Exception` does not do anything extra besides triggering the TPE, and thus (in my opinion) it should be as clear as possible from the code.

2021-03-08 12:32 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +            raise Exception("JupyterLab build in progress. Cannot start session.")
I think that having a specific exception related to "triggering" the TPE would in some sense imply that there is logic that acts differently based on that, although I don't think that should be the case.  
Maybe the type `Exception` could be replaced with one more specific, but having a TPE specific exception to show intent might not be that useful given that raising an exception is already telling that the code path cannot continue, in a certain sense the code in `TwoPhaseFunction` should not care about the type of exceptions it raises.

Maybe some more input on this would help, @ricklamers?

2021-03-08 17:36 UTC, ricklamers commented on services/jupyter-server/start.sh
> +cp -rnT "$build_path/extensions" "$userdir_path/extensions"
This is different, this just copies _new_ extensions that might have been created in the `$build_path` during the image build of JupyterLab. This is because of the `-n` flag for `cp`.

2021-03-08 17:37 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        ).first()
I think this doesn't fit here. Because the particular check is never supposed to be called from outside the `orchest-api`. So adding it to `namespace_validations` feel wrong.

2021-03-08 17:49 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +            raise Exception("JupyterLab build in progress. Cannot start session.")
I agree with @fruttasecca. Although I think Yannick correctly identified that raising a generic exception is problematic. It's now a custom exception that is handled in the TPE execution part.

2021-03-08 17:54 UTC, ricklamers commented on services/orchest-api/app/app/core/sessions.py
> +        )
It's an explicit choice to make the image name dependent on the Orchest version. Whenever Orchest is updated the JupyterLab image on which the setup_script builds can be changed in arbitrary ways. Thus we always want to rebuild the JupyterLab image whenever Orchest is updated (instead of doing any clever checking to see if it's necessary to rebuild the JupyterLab image).

Make the Orchest version part of the name of the JupyterLab image makes this simple. Orchest just checks whether this Orchest's version JupyterLab image exists, if it doesn't it uses the base JupyterLab image that's included with Orchest when starting a session.

During boot of Orchest a build of the JupyterLab image is triggered if it detects that the user has a JupyterLab setup_script but no JupyterLab image built for the current version of Orchest.

I don't see how this behavior would be possible if you use the `:latest` tag (I think you mean overwriting the JupyterLab base image that comes with Orchest, but that would make rebuilding the `setup_script` starting from the clean bundled base JupyterLab image impossible).

2021-03-08 17:58 UTC, ricklamers commented on services/orchest-api/app/app/apis/namespace_jupyter_builds.py
> +            AbortJupyterBuild(self.tpe).transaction(build.uuid)
You can't actually trigger this from the GUI, as the build button is hidden when a build is in progress. But in case the network request does make it through, the robust thing is to cancel the JupyterLab build. As there can only ever exist on JupyterLab user image at once anyway.

2021-03-08 18:00 UTC, ricklamers commented
Thank you :smiley:!

>When it comes to the documentation, what do you think about putting it in Other, or do we want to have a complete section about IDE configurations? It is quite the feature I think.

I think the location I used 'Installing additional packages' currently makes the most sense (given the table of contents of the docs).

2021-03-09 07:53 UTC, yannickperrenet commented on services/jupyter-server/start.sh
> +cp -rnT "$build_path/extensions" "$userdir_path/extensions"
> This is because of the -n flag for cp.

I know that ;)

Giving it a second look, I guess it was moved upwards so that the extensions the user installs (through the bash script) will be copied to the userdir path as well. Am I right?

If this is the case, then the comments should reflect this. To me this was not obvious from the current comments.

2021-03-09 08:00 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        ).first()
I get what you are saying, but the current structure of the `orchest-api` allows utility functions to be added to `namespace_*` files that can be imported in other namespaces. Remember going with this approach over creating a `utils_*` file for every namespace. So due to that structure I would say it is fine putting it in the `namespace_validations.py`

@fruttasecca What do you think?

2021-03-09 08:03 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +    pass
This should be moved to a `error.py` as well.

2021-03-09 08:06 UTC, yannickperrenet commented
> 'Installing additional packages' currently makes the most sense

I disagree here. "Installing additional packages" is about installing packages such as `tensorflow`, not jupyterlab extensions, which in my opinion is a totally different context.

I will go over the newly written section in the docs and see whether I can come up with another place to put it.

2021-03-09 08:17 UTC, yannickperrenet commented
When opening the pipeline editor, whilst doing a JupyterLab build the user is greeted with the error saying "Cannot start session. A JupyterLab build is still in progress.". The error is triggered because we automatically try to start the session (if none is active) when a user opens the pipeline editor.

I think, instead, we should not automatically try to start the sessions (since we can check whether the build is in progress). Then if a user wants to start a session, then it is fine to get the error. I would rather not give a user an error if we can prevent it.

To achieve this behavior we would have to discuss it in https://github.com/orchest/orchest/pull/163#discussion_r590046482 as well.

2021-03-09 08:23 UTC, yannickperrenet commented on services/orchest-api/app/app/core/sessions.py
> +        )
> Making the Orchest version part of the name of the JupyterLab image makes this simple. Orchest just checks whether this Orchest's version JupyterLab image exists, if it doesn't it uses the base JupyterLab image that's included with Orchest when starting a session.

This is a different approach from the environment images. Whenever Orchest is updated, we remove all environment build images (refer to [orchest-ctl update](https://github.com/orchest/orchest/blob/feature-jupyterlab-server-extensions/services/orchest-ctl/app/orchest.py#L295)). Similarly, whenever Orchest is updated all JupyterLab builds should be removed.

Using that approach, the Orchest version no longer needs to be included in the image name and we can just use the `:latest` tag to get the most up-to-date image whenever a user does multiple builds (without updating Orchest in between).

2021-03-09 10:15 UTC, ricklamers commented
Some thoughts on why I'd prefer to keep it the way it is currently:

- I think it's inconsistent to 'silently' disable autostart when JupyterLab is building in the background.
- When a JupyterLab build is triggered (which can happen from the back-end as well, for example during start, similar to how migrations work) it should also fail if there are sessions running. So this validation should be part of the build TPF.
- I think the code is too short to factor our into a utility function that is in namespace_validations. This isn't exact science imo. But my heuristic is roughly: if I don't know any other caller and it's a short piece of code, I don't abstract it out.
- The JupyterLab image name with the version is more robust, as it will not be possible to load an outdated JupyterLab after update (even if for example the removal of the JupyterLab use image did not succeed)

2021-03-09 10:17 UTC, ricklamers commented
> I will go over the newly written section in the docs and see whether I can come up with another place to put it.

I like your changes to the docs! It does it more justice like this and is more cleanly separated from the environment packages (to avoid confusion).

2021-03-09 10:27 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_sessions.py
> +        ).first()
I think this might have to go in validations so that it can easily become an exposed endpoint/gate check in the future.

>I think, instead, we should not automatically try to start the sessions (since we can check whether the build is in progress). Then if a user wants to start a session, then it is fine to get the error. I would rather not give a user an error if we can prevent it.

In any case, I think another problem would be that from the pipeline editor I would have to try out starting a session to know if a session can be started or not without changing views.

2021-03-09 11:28 UTC, yannickperrenet approved these changes

2021-03-09 13:12 UTC, fruttasecca approved these changes
lgtm, great PR

2021-03-09 17:04 UTC, merged