Add cloud mode
orchest/orchest pull request #176
Opened 2021-03-15 11:44 UTC by fruttasecca

## Description

This PR adds another mode in which Orchest can be run, `cloud`. Currently this only implies that some settings cannot be modified through the GUI. Cloud mode can be seen as a "regular" production mode, with some changes on top of it. This means that it does not have the interactivity of `dev` mode.

### Checklist

- [ ] The documentation reflects the changes.
- [X] I have manually tested the application to make sure the changes don’t cause any downstream issues.

- [X] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

2021-03-15 12:00 UTC, yannickperrenet commented on services/orchest-ctl/app/cli/start.py
> +    mode and telemetry_disabled are not modifiable through the GUI.
I suggest making it into:
```suggestion
    Running Orchest in CLOUD mode changes GUI functionality. For 
    example making it impossible to disable the authentication layer.
```
because otherwise the comment might quickly become outdated.

After additional functionality it should probably become a section in the docs (as you noted).

2021-03-15 12:03 UTC, yannickperrenet commented on services/orchest-webserver/app/app/config.py
> +    _CLOUD_UNMODIFIABLE_SETTINGS = [
`_CLOUD_UNMODIFIABLE_CONFIG_VALUES` makes more sense to me.

2021-03-15 12:08 UTC, yannickperrenet commented on services/orchest-webserver/app/static/js/src/views/SettingsView.js
> +                      modified in cloud mode.
* `cloud` should also be `<span className="code">cloud</span>`.
* The version information in settings should now also contain `cloud`. Or we could just remove: "The application mode can either be: production or development", since for cloud users it will always be cloud and thanks to this PR we can finally make that distinction.

2021-03-15 12:10 UTC, yannickperrenet commented on services/orchest-webserver/app/static/js/src/views/SettingsView.js
> +            shouldReload = configJSON.AUTH_ENABLED && !authWasEnabled;
Why is this done? Doesn't really make sense to me, because for other users that connect to Orchest the authentication would be enabled. Now the user just gets "thrown" out of Orchest. 

On another note, enabling authentication should not be possible without having configured a single user.

@ricklamers Do you want to chip in here?

2021-03-15 12:20 UTC, yannickperrenet commented on services/orchest-webserver/app/app/views/views.py
> +                save_user_conf_raw(json.dumps(config))
To me it is a bit unclear what is being done here (including in the `update_orchest_config` function).

2021-03-15 12:22 UTC, yannickperrenet requested changes
The way it is implemented now would require the `_CLOUD_UNMODIFIABLE_SETTINGS` to be set in the `config.json` beforehand. So instead of setting a default value in the code for the `cloud` mode, the default value is assumed to be set in the `config.json`. 

Not sure whether that is something we want.

Additionally, I think the updating mechanism is a little hard to follow from a code perspective.

2021-03-15 13:55 UTC, fruttasecca commented on services/orchest-webserver/app/static/js/src/views/SettingsView.js
> +                      modified in cloud mode.
>Or we could just remove: "The application mode can either be: production or development"

Would that also imply removing the `Application mode: production` on the right? If so, I would go for that since it's less text that the user has to look at.

2021-03-15 13:56 UTC, fruttasecca commented on services/orchest-webserver/app/static/js/src/views/SettingsView.js
> +            shouldReload = configJSON.AUTH_ENABLED && !authWasEnabled;
>Now the user just gets "thrown" out of Orchest.

In that regard, the PR does not alter functionality.

>On another note, enabling authentication should not be possible without having configured a single user.

We would need to expand the API of the `auth-server` I think.

2021-03-15 14:21 UTC, fruttasecca commented
> The way it is implemented now would require the `_CLOUD_UNMODIFIABLE_SETTINGS` to be set in the `config.json` beforehand. 

I think this is untrue, each one of those settings has a default value set in the code if they are not set already, although said values are set in a somewhat scattered way.

2021-03-15 16:41 UTC, yannickperrenet commented on services/orchest-ctl/app/cli/start.py
> +    directly, which can be found at ~/.config/orchest/config.json.
This path is not 100% true as the `$XDG_CONFIG_HOME`  variable takes precedence if set. Maybe make it "'config.json' configuration file".

2021-03-15 16:46 UTC, ricklamers commented on services/orchest-webserver/app/static/js/src/views/SettingsView.js
> +            shouldReload = configJSON.AUTH_ENABLED && !authWasEnabled;
If a user enables authentication, and the page is not reloaded, iframes and endpoint requests start to get redirected to the login page. I felt reloading the page when auth is enabled is nice, because it redirects to the login screen to create a session, or is a (almost, just page reloading) no-op in case an authenticated session is in place.

2021-03-15 16:50 UTC, yannickperrenet commented on services/orchest-webserver/app/static/js/src/views/SettingsView.js
> +            shouldReload = configJSON.AUTH_ENABLED && !authWasEnabled;
I see. In that case I understand why the page is refreshed, but from a user interaction I don't like that it is.

Take again my example where you could basically lock your Orchest installation as you can enable authentication without having a single user defined.

2021-03-15 16:52 UTC, ricklamers commented on services/orchest-webserver/app/static/js/src/views/SettingsView.js
> +                return <p>Find out Orchest's version.</p>;
This should be changed before the PR merges I think.

This cloud|development|production is a bit of a modeling error perhaps. I think it should still just be development|production and the "cloud" flag should be an orthogonal concern.

2021-03-15 17:25 UTC, yannickperrenet commented
I just discussed with @ricklamers and we decided it would be better to remove the notion of a `mode` in Orchest, meaning that `cloud` and `dev` would become flags.

This then also affects the documentation and general wording in the CLI.

@fruttasecca Let me know if you strongly disagree.

2021-03-16 09:57 UTC, fruttasecca commented
@yannickperrenet @ricklamers 

I guess we are removing such notions at the GUI level as well, right?
![image](https://user-images.githubusercontent.com/19429509/111290353-5e213780-8646-11eb-9f40-d8005019502c.png)

2021-03-16 10:14 UTC, yannickperrenet commented
> I guess we are removing such notions at the GUI level as well, right?

For example Flask does call it "development mode". 

@ricklamers Was the main advocate for making it flags instead of separate commands, so I will let him make the decision here.

2021-03-16 10:19 UTC, ricklamers commented
> I guess we are removing such notions at the GUI level as well, right?

I think the best thing to do would be to indicate that the development flag is enabled. The notion of a 'mode' should I think be removed.

2021-03-17 08:39 UTC, yannickperrenet commented on services/orchest-webserver/app/static/js/src/views/SettingsView.js
> +            shouldReload = configJSON.AUTH_ENABLED && !authWasEnabled;
Can we add a comment to the config section that if a user enabled authentication, they will be automatically redirected to the login page?

2021-03-17 08:51 UTC, yannickperrenet commented on services/orchest-ctl/app/cli/main.py
> +            "instead of --mode=dev."
Why don't we remove it in this PR already?

2021-03-17 10:16 UTC, fruttasecca commented on services/orchest-ctl/app/cli/main.py
> +            "instead of --mode=dev."
Because of the way the updating mechanism works. Updating from the client means pulling the up to date `ctl` image, then sending a `restart` command to it, but the image sending the command will be the "old" one, which still relies on this option. (Assuming I am correct :P)

2021-03-17 10:27 UTC, yannickperrenet commented on services/orchest-ctl/app/cli/main.py
> +            "instead of --mode=dev."
Yes, the update mechanism is quite complex. Good catch.

@ricklamers Do you think it is time to revision the update mechanism? This is definitely not the first time we are running into issues for updates.

2021-03-17 10:29 UTC, ricklamers commented on services/orchest-ctl/app/cli/main.py
> +            "instead of --mode=dev."
@fruttasecca and I spent a bit of time reviewing how we could handle this better (or refactor things to avoid it in the future). As of now, it seems like there aren't strictly better solutions available. The update mechanism isn't wrong by design, it's just a complicated feature.

We can review/refactor/improve in the future. But quick wins seemed out of sight.

2021-03-17 12:36 UTC, yannickperrenet approved these changes

2021-03-17 13:57 UTC, merged