Add single param get/update for step, pipeline
orchest/orchest pull request #202
Opened 2021-04-13 12:42 UTC by fruttasecca

## Description
This PR expands the Orchest SDK to add single parameter `get` and `update` operations for both step and pipeline parameters.
It's still possible to `get` or `update` parameters in a batched manner by using the `get_params` and `update_params` functions.

Signatures:
`def get_step_param(key: str) -> Any:`
`def get_pipeline_param(key: str) -> Any:`
`def update_step_param(key: str, value: Any) -> None:`
`def update_pipeline_param(key: str, value: Any) -> None:`

### Checklist
- [X] The documentation reflects the changes.
- [X] I have manually tested the application to make sure the changes don’t cause any downstream issues.
- [X] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

2021-04-13 12:53 UTC, yannickperrenet commented on orchest-sdk/python/orchest/__init__.py
> +)
Do we want to expose all of these functions directly? I think we should only expose our "recommended" functions and let the users import the `parameters` module themselves to get another function.

2021-04-13 12:54 UTC, yannickperrenet commented on orchest-sdk/python/orchest/parameters.py
> +def __get_pipeline() -> Pipeline:
Why the double leading underscores instead of single?

2021-04-13 12:56 UTC, fruttasecca commented on orchest-sdk/python/orchest/__init__.py
> +)
I would leave them exposed, they are part of the SDK so I see no reason in creating a discrepancy.

2021-04-13 12:57 UTC, yannickperrenet commented on orchest-sdk/python/orchest/parameters.py
> +    """
The documentation reads "step parameter name" and "step by name", but the function signature is "key". Unsure how exactly users think about defining the JSON in the UI, do they think of it as "key"s or "parameter"s. My guess is the second and thus I would opt for changing `key: str` to `param_name: str`

2021-04-13 12:58 UTC, fruttasecca commented on orchest-sdk/python/orchest/parameters.py
> +def __get_pipeline() -> Pipeline:
No particular reason, can make it into a single.

2021-04-13 12:59 UTC, yannickperrenet commented on orchest-sdk/python/orchest/parameters.py
> +def update_step_param(key: str, value: Any) -> None:
I think this function should internally call the `update_params`.

2021-04-13 13:02 UTC, yannickperrenet requested changes
A few minor wording changes have to be made.

On another note, shouldn't we go for something like a class instead of defining all these functions? For example:
```python
class Params:
  def get(name: str) -> Any
```
Although this is less inline with the `transfer` module. Just wanted to share my thought of taking a more class oriented approach.

2021-04-13 13:04 UTC, yannickperrenet commented on orchest-sdk/python/orchest/parameters.py
> +def __get_pipeline() -> Pipeline:
Yes, I prefer single as it is inline with PEP8.

2021-04-13 13:20 UTC, fruttasecca commented
> A few minor wording changes have to be made.
> 
> On another note, shouldn't we go for something like a class instead of defining all these functions? For example:
> 
> ```python
> class Params:
>   def get(name: str) -> Any
> ```
> 
> Although this is less inline with the `transfer` module. Just wanted to share my thought of taking a more class oriented approach.

Given the limited scope of the parameters module I think we can leave it as it is right now.

2021-04-13 13:36 UTC, yannickperrenet commented on orchest-sdk/python/orchest/__init__.py
> +)
We do the same for the `transfer` module. And I would argue that exposing functionality top-level exactly justifies the introduction of such a discrepancy. We can define exactly the function top-level which should be used by the user (in most cases).

2021-04-13 13:44 UTC, fruttasecca commented on orchest-sdk/python/orchest/__init__.py
> +)
What I dislike is that we would have that a rather "obvious" functionality, i.e. getting all the params, is not exposed. I don't feel strongly about this so I am fine going either way since the user can just import `parameters`, let me know if I should pull the trigger.

2021-04-13 13:47 UTC, yannickperrenet commented on orchest-sdk/python/orchest/__init__.py
> +)
I think the main power is that we can choose what we want to expose at the top-level and thus pointing users to use certain functions rather than others. So I would rather not make "getting all the params" and "updating all the params" top-level, and let users import `parameters` to get the functionality.

2021-04-13 13:58 UTC, yannickperrenet approved these changes

2021-04-13 14:06 UTC, merged

2021-05-15 09:18 UTC, ricklamers commented
Note, we should have incremented the SDK version to reflect the API change.