Initial TypeScript implementation
orchest/orchest pull request #207
Opened 2021-04-15 06:28 UTC by joe-bell

## Description

### Checklist

- [ ] The documentation reflects the changes.
- [ ] I have manually tested the application to make sure the changes don’t cause any downstream issues.

- [ ] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

2021-04-15 12:59 UTC, joe-bell commented on .pre-commit-config.yaml
> +        files: \.(js|jsx|json|ts|tsx|html|css|scss)$
@yannickperrenet I think you'll be chuffed to see this - now this only runs on _these_ specific file types (not all files, like before)

2021-04-16 06:32 UTC, ricklamers commented
This looks like a good initial step of adding TypeScript.

Two questions:

- It looks like the pnpm linter is now being skipped in the GitHub Action. Or am I seeing that incorrectly?
- I think the Dockerfile pnpm build needs to receive the updated filter (not sure if it’s referenced anywhere else)

2021-04-19 12:24 UTC, joe-bell commented
@ricklamers thanks!

1. It does, but [we run it manually instead](https://github.com/orchest/orchest/pull/207/files#diff-ac5eead3f3ce4863c524fff031a87b7aecccb4a0493df087a4e1c704a1505036R31) (the build script will catch out any type errors too). I spent an hour or two debugging this and trying to get it working in Precommit (you can see the commits haha), but I don't think it's worth spending more time on this
2. Fixed, thank you!

2021-04-19 12:50 UTC, ricklamers requested changes

2021-04-19 12:50 UTC, ricklamers commented on .github/workflows/pre-commit.yml
> +        run: npm run setup && pnpm install && pnpm run build
The pre-commit should not run a full build IMO. For pre-commit I'd rather stick to formatters & linters at most. Limiting their execution time. If you want to build for verification it should be in the test suite not in the pre-commit hook.

2021-04-19 12:53 UTC, joe-bell commented on .github/workflows/pre-commit.yml
> +        run: npm run setup && pnpm install && pnpm run build
This is the GitHub action workflow – it only tiggers as part of the review step, **not** locally

If you'd prefer I can create a new GitHub Action to run this @ricklamers

2021-04-20 07:14 UTC, ricklamers commented on .github/workflows/pre-commit.yml
> +        run: npm run setup && pnpm install && pnpm run build
Nevermind, I’m apparently blind 😅

2021-04-20 13:29 UTC, joe-bell commented
That last commit made me feel dirty, but it'll work for now…

Let's consider ditching `react-codemirror2` in the future to avoid this `global is not defined` issue

2021-04-20 16:16 UTC, ricklamers approved these changes

2021-04-20 16:16 UTC, merged