Expand Orchest API tracking
orchest/orchest pull request #225
Opened 2021-05-03 09:26 UTC by fruttasecca

## Description
This PR expands the anonymized tracking of the Orchest API.

### Checklist

- [X] The documentation reflects the changes.
- [X] I have manually tested the application to make sure the changes don’t cause any downstream issues.
- [X] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

2021-05-03 09:31 UTC, ricklamers commented
The changes to existing events to my knowledge are:

pipeline run --> pipeline_run start

Is there more? I think it isn't problematic.

2021-05-03 09:40 UTC, fruttasecca commented
@ricklamers I've updated the PR description.

2021-05-04 16:24 UTC, yannickperrenet commented on services/orchest-webserver/app/app/views/orchest_api.py
> +)
This is just my opinion so you don't have to change it, but I generally like doing `from app import analytics` and call `analytics.funcname` instead mainly because of the expressiveness as it becomes clear that `funcname` is an `analytics` function (plus it cleans up the imports).

2021-05-04 16:26 UTC, yannickperrenet commented on services/orchest-webserver/app/app/analytics.py
> +    req.pop("project_path")
Seems unnecessary as the `props` don't include the `project_path` nor the entire `req` object.

2021-05-04 16:31 UTC, yannickperrenet commented on services/orchest-webserver/app/app/analytics.py
> +    run_spec.pop("pipeline_run_spec", {}).pop("pipeline_path", None)
Not really sure what you are trying to do here. But my guess is you are trying to do:
```python
run_spec["pipeline_run_spec"].pop("host_user_dir")
```
Calling `pop` on the `run_spec` directly will remove `"pipeline_run_spec"` in its entirety.

2021-05-04 16:33 UTC, yannickperrenet requested changes
I like the additional information this gives us whilst keeping it anonymized and considering that file names etc. are not included.

2021-05-05 09:22 UTC, fruttasecca commented on services/orchest-webserver/app/app/analytics.py
> +    run_spec.pop("pipeline_run_spec", {}).pop("pipeline_path", None)
The entire snippet of code is kinda botched, will fix

2021-05-05 09:23 UTC, fruttasecca commented on services/orchest-webserver/app/app/views/orchest_api.py
> +)
Good idea, will fix

2021-05-05 15:03 UTC, yannickperrenet approved these changes

2021-05-05 15:05 UTC, merged