Use a different logger when running as celery
orchest/orchest pull request #305
Opened 2021-06-09 10:56 UTC by fruttasecca

## Description
Fixes an issue where code shared by the `orchest-api` and `celery-worker` would fail because it contained a resource that was not available to the `celery-worker`, the app logger.

### Checklist

- [X] I have manually tested the application to make sure the changes don’t cause any downstream issues, which includes making sure `./orchest status --ext` is not reporting failures when Orchest is running.

2021-06-09 11:03 UTC, ricklamers approved these changes

2021-06-09 11:03 UTC, ricklamers commented
LGTM!

2021-06-09 17:52 UTC, yannickperrenet requested changes
I would like a short discussion wrt logging before merging this.

2021-06-10 07:10 UTC, fruttasecca commented
To bring some more context:
- `logging.error` is used by services that do not run `flask` or `celery`
- `current_app.logger` is used by services running flask
- `utils.get_logger` is used by code that is shared between a service running `flask` and a service running `celery`

What we could do is move `get_logger` in the internal library but that would require the internal library adding `celery` & `flask` to its requirements, or a clever hack that, in a cascading manner, tries to import `flask` and `celery` returning the first logger it is able to get, with fallback to the `logging` module.

2021-06-10 07:20 UTC, yannickperrenet commented
> What we could do is move get_logger in the internal library but that would require the internal library adding celery & flask to its requirements, or a clever hack that, in a cascading manner, tries to import flask and celery returning the first logger it is able to get, with fallback to the logging module.

I prefer taking this approach, given that we can make it a "smart" implementation. This way we encapsulate all logging calls so that developers do not have to be aware of your aforementioned rules.

Maybe something along the lines of
```python
try:
    import celery
except ModuleNotFoundError:
    ....
```

2021-06-10 07:24 UTC, fruttasecca commented
Yeah that would be the approach to go for the implementation. Happy to take care of this but it should be in a different PR imo.

2021-06-10 07:27 UTC, ricklamers commented
Agree it should be a different PR. Not exactly sure if such a logger get utility is preferable as a util. The internal function is then tied to the implementation details of its consumers (i.e. it needs to know about Celery and Flask). Sounds like a code smell to me.

2021-06-10 07:34 UTC, yannickperrenet commented
> Happy to take care of this but it should be in a different PR imo.

That works for me!

> Sounds like a code smell to me.

To me it doesn't. It is a utility after all.

2021-06-10 07:35 UTC, yannickperrenet approved these changes

2021-06-10 07:48 UTC, fruttasecca commented
I think it's not super clean as well but it's a tradeoff. One issue I can see with this approach is that it might introduce some kind of leaky abstraction, given that a service would get its logger from said function while having to configure it, which means we will be operating under the assumption that the logger retrieved through said function and the configuration set by the service are pointing to the same logger.
It doesn't look like the logging configurations are exactly the same, i.e. there are some unique service related entries.

2021-06-10 07:51 UTC, merged