Fix query args passing at `/login`
orchest/orchest pull request #383
Opened 2021-07-12 17:27 UTC by yannickperrenet

## Description

The view to load (either `login` or `admin`) in the `auth-server` was determined by 
```javascript
let view = window.location.href.split("/").slice(-1)[0];
```
which incorrectly handles URLs such as `http://localhost:8000/login?redirect_url=/environments` (`view` would be `environments`).

This PR fixes the issue, making the following possible again:
* http://localhost:8000/login?redirect_url=/environments
*  http://localhost:8000/login?redirect_url=/projects&import_url=https://github.com/orchest/quickstart

> FYI the issue was (unknowingly) reintroduced in a6770357512250425ac927aa1cae6227ed760f1f.

2021-07-12 18:28 UTC, ricklamers commented
The `/login` endpoint has a different JS client altogether.

Hence, I don’t think this ever caused an issue. Although arguably the new way to determine the first path component is more robust.

2021-07-12 18:31 UTC, ricklamers commented on services/auth-server/client/src/App.tsx
> +    const view = window.location.pathname.split("/")[1];
This will parse the URL on each app render, this is undesirable. This code should still only run when the root React component is first initialized.

2021-07-12 18:34 UTC, ricklamers commented on services/auth-server/app/app/views.py
> +                    # Returns a shallow mutable copy of the immutable
The `redirect_url` should include any query arguments if necessary. The other query arguments shouldn’t be passed.

2021-07-12 18:37 UTC, ricklamers requested changes
See comments

2021-07-12 18:48 UTC, ricklamers commented
Please pay attention to the fact that the full redirect_url will be/should be properly URL encoded.

`/login?redirect_url= %2Fprojects%26import_url%3Dhttps%3A%2F%2Fgithub.com%2Forchest%2Fquickstart`

2021-07-13 06:49 UTC, yannickperrenet commented on services/auth-server/app/app/views.py
> +                    # Returns a shallow mutable copy of the immutable
Not sure I follow here, because something like http://localhost:8000/login?redirect_url=/projects&import_url=https://github.com/orchest/quickstart should also work which contains two query arguments: `redirect_url` and `import_url`. Good to note here that `import_url` only works on the `/projects` view.

2021-07-13 06:54 UTC, yannickperrenet commented on services/auth-server/client/src/App.tsx
> +    const view = window.location.pathname.split("/")[1];
Will move :+1:

2021-07-13 08:16 UTC, fruttasecca approved these changes

2021-07-13 08:25 UTC, joe-bell approved these changes

2021-07-13 08:33 UTC, merged