Update to JupyterLab 3.0.0
orchest/orchest pull request #59
Opened 2020-11-16 15:14 UTC by ricklamers

Update to support JupyterLab 3.0.0 (rc.9).

It gets rid of the need to patch the reconnect procedure for the enterprise gateway which previously resulted in significant compile times for the jupyter-server service image.

This PR also removes the need for token based authorization of the JupyterLab instance since we authenticate all requests through the nginx proxy. This simplifies the jupyter-server spawning by just starting JupyterLab through the CLI instead of directly calling into it's Python classes (they provide a more stable interface on the CLI compared to direct Python initialization).

2020-11-16 16:27 UTC, fruttasecca commented on services/jupyter-server/Dockerfile
> +    flask_socketio \
```suggestion
    flask_socketio \
    requests \
```
Should we pin down the versions?

2020-11-16 16:27 UTC, fruttasecca commented on services/jupyter-server/Dockerfile
> +    flask_socketio \
Should we pin down the versions?

2020-11-16 16:29 UTC, fruttasecca commented on services/jupyter-server/app/requirements.txt
> +jupyterlab
Should we pin down the version?

2020-11-16 16:35 UTC, fruttasecca reviewed
lgtm, apart from the fact that we should pin down versions more often when it comes to the requirements

2020-11-17 07:15 UTC, yannickperrenet commented
As discussed we will try a larger rewrite where we no longer require the JupyterLab to be wrapped in a Flask API. Basically converting the into a Dockerfile with an `ENTRYPOINT`.

2020-11-17 15:51 UTC, ricklamers commented on services/jupyter-server/app/requirements.txt
> +jupyterlab
No longer exists.

2020-11-17 16:31 UTC, yannickperrenet commented on services/orchest-api/app/app/core/sessions.py
> +            ),
I think this would be clearer:
```python
"base_url": "/" + _config.JUPYTER_SERVER_NAME.format(
                project_uuid=project_uuid[: _config.TRUNCATED_UUID_LENGTH],
                pipeline_uuid=pipeline_uuid[: _config.TRUNCATED_UUID_LENGTH],
            ),
```

2020-11-17 17:56 UTC, yannickperrenet commented on services/jupyter-server/Dockerfile
>      Werkzeug==0.16.1
Can we use a `requirements.txt` instead just like with other services.

2020-11-17 17:59 UTC, yannickperrenet commented on services/jupyter-server/Dockerfile
>  RUN mkdir /root/.jupyter/
Don't think this line is needed as the `COPY` command should needed paths.

2020-11-17 18:01 UTC, yannickperrenet commented on services/jupyter-server/Dockerfile
Should probably also add the line
```
LABEL maintainer="Orchest B.V. https://www.orchest.io"
```

2020-11-17 18:03 UTC, yannickperrenet commented on services/jupyter-server/Dockerfile
>  RUN jupyter labextension install /jupyter-extensions/orchest-integration
Should probably make this into a one-line `RUN` command with `&&` as otherwise it would create two Docker layers.

2020-11-17 18:06 UTC, yannickperrenet commented on services/orchest-api/app/app/core/sessions.py
>          #       DELETE request to the flask API inside the jupyter-server
The `shutdown_jupyter_server` used below does it gracefully, so we should remove this comment.

2020-11-17 18:36 UTC, yannickperrenet commented on services/orchest-api/app/app/core/sessions.py
> -            "ServerApp.base_url": f'/jupyter_{IP.jupyter_server.replace(".", "_")}/',
Sadly, GitHub did not allow me to put the comment there. But I would like to also remove the comments

```python
# The launched jupyter-server container is only running the API
# and waits for instructions before the Jupyter server is
# started. Tries to start the Jupyter server, by waiting for the
# API to be running after container launch.
```
a few lines above.

2020-11-17 18:40 UTC, yannickperrenet requested changes
I love the reduced complexity! Just need some small changes.

2020-11-18 10:08 UTC, ricklamers commented on services/orchest-api/app/app/core/sessions.py
> -            "ServerApp.base_url": f'/jupyter_{IP.jupyter_server.replace(".", "_")}/',
Anything in particular about the docstring?

```
"""Launches the interactive session.

Additionally connects the launched `jupyter-server` with the
`jupyter-enterprise-gateway` (shot `jupyter-EG`).

Args:
    See `Args` section in parent class :class:`Session`.

"""
```

Seems to cover it?

2020-11-18 10:32 UTC, fruttasecca approved these changes
lgtm, might have to change a couple of things if you agree with it

2020-11-18 10:32 UTC, fruttasecca commented on lib/python/orchest-internals/_orchest/internals/config.py
> +TRUNCATED_UUID_LENGTH = 18
I think it could be wise to explain why only some lengths are valid, e.g. otherwise you might get hostnames
ending with an hyphen.

2020-11-18 10:32 UTC, fruttasecca commented on services/jupyter-server/Dockerfile
> +RUN rm /bin/sh && ln -s /bin/bash /bin/sh
Can these be squashed into a single RUN command?

2020-11-18 10:59 UTC, ricklamers commented on services/jupyter-server/Dockerfile
> +RUN rm /bin/sh && ln -s /bin/bash /bin/sh
These RUNs are pretty much unrelated, I like the separation between them and the overhead of multiple layers is quite minimal in this case I believe.

2020-11-18 11:02 UTC, ricklamers commented on lib/python/orchest-internals/_orchest/internals/config.py
> +TRUNCATED_UUID_LENGTH = 18
Good one! Added to the comment.

2020-11-18 11:03 UTC, merged