Environment consistency across steps and runs on environment rebuilds
orchest/orchest pull request #64
Opened 2020-11-19 16:07 UTC by fruttasecca

This PR introduces the concept of a dangling image from the point of view of orchest.
A dangling image is an image that is nameless, tag-less and that no further pipeline run (PENDING or STARTED) is going to
use.
An environment image might become nameless and tag-less on an environment rebuild, where it essentially becomes outdated.

Upon queuing an interactive run or an experiment, a reference to all images used by every step/run is maintained so that
consistency is preserved in the case of an environment rebuild that happens while the run/experiment is being executed. 
From the point of view of the user, queuing a run or an experiment takes a snapshot of the current state of the environment images.
Upon terminating a run, each environment image that was used is removed if it is now dangling, which means this run
was effectively the last run using it.

The implementation mostly consist in new models, new api endpoints and an update on the endpoints that are actually
launching pipelines runs. 
The entire PR affects only the orchest-API.

Things to discuss: 
- In a previous discussion with Rick we got to the conclusion that we would need to add 2 new models 
   (NonInteractiveRunImageMapping, InteractiveRunImageMapping) to maintain the mapping between the run and what images 
  it uses, I wonder if we can instead get rid of them and add the needed columns to the PipelineStep model

2020-11-19 16:55 UTC, yannickperrenet commented
Please correct me if I am wrong. 

This PR creates a new endpoint in `namespace_environment_images.py` and `namespace_runs.py` that removes dangling images w.r.t. Orchest, i.e. Orchest is not using the image currently and will not use the image in the future. And then we will also need to update database entries outside of these endpoints for database consistency.

2020-11-19 17:01 UTC, fruttasecca commented
> Please correct me if I am wrong.
> 
> This PR creates a new endpoint in `namespace_environment_images.py` and `namespace_runs.py` that removes dangling images w.r.t. Orchest, i.e. Orchest is not using the image currently and will not use the image in the future. And then we will also need to update database entries outside of these endpoints for database consistency.

Which entries are you referring to?

2020-11-20 07:55 UTC, yannickperrenet commented on services/orchest-api/app/app/core/pipelines.py
> +        return list(set([step.properties["environment"] for step in self.steps]))
I don't think this should be a `property`. Probably `.get_environments(self)` is better because the property does not support assignment.

2020-11-20 08:01 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +            # end up with mappings that are pointing to an image that does not exist
So this means that the environments of the pipeline at the moment that the experiment is started by the user, do not  have to be the environments that are used during the experiment?

2020-11-20 08:05 UTC, yannickperrenet commented on services/orchest-api/app/app/utils.py
> +    return docker_client.images.get(name_or_id).id
The `return` should probably be wrapped in a try-except block.

2020-11-20 08:23 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_runs.py
> +class ProjectDanglingEnvironmentImages(Resource):
What is the need of this endpoint given that there is a similar one in `namespace_environment_images.py`?

2020-11-20 08:30 UTC, yannickperrenet requested changes
Overall I think there are too many things happening in too many places, causing me to somewhat lose the overview of what is happening. It should be clear exactly what happens when, for example, an interactive run is started.

Secondly, we should start moving code into functions as certain blocks are repeated between endpoints.

Lastly, could you also wrap your comments and docstrings at a maximum line length of 72 (for PEP8). It seems like black does not format comments, but currently some are too long to fit on my (split) screen.

2020-11-20 08:37 UTC, fruttasecca commented on services/orchest-api/app/app/core/pipelines.py
> +        return list(set([step.properties["environment"] for step in self.steps]))
Agree

2020-11-20 08:56 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +            # end up with mappings that are pointing to an image that does not exist
>So this means that the environments of the pipeline at the moment that the experiment is started by the user, do not have to be the environments that are used during the experiment?

This happens when the experiment is queued. About them potentially not being the exact same environment as when the user queues an experiment in the GUI: given the speed at which the request is resolved, if an environment finishes building in between a request getting resolved (actually, between the moment we read the docker ids and commit to db), the environment might very well have finished building right before the moment the user had clicked to queue an experiment through the GUI. 

If we want to get to this level of snapshotting then the client would have to know the docker ids beforehand, queue an experiment along with the docker ids to use, which might still lead to race conditions (e.g. an image getting rebuilt, becoming nameless and then deleted), except that now we have to maintain consistent docker ids in the client.

>Secondly, what is the benefit of explicitly checking whether they have become "nameless" because the moment this check passes they could become nameless again and thus ending up in the same situation. In other words, I don't see what this block solves or am I missing something obvious?

It resolves a race condition.
If an image has become nameless then a call to delete it as a dangling image might be on its way to delete the image. See `remove_if_dangling` in `services/orchest-api/app/app/utils.py`. 

Essentially, if an image has not become nameless after we have committed to db, then for sure this image won't be deleted, since `remove_if_dangling` will check for two things: if the image is nameless and if the image is/will be used (there are commits to the db showing that this image is used by a run that is PENDING or STARTING). 

If we discover that an image has become nameless after we have committed, then it could be that `remove_if_dangling`
has actually passed its checks before we could commit to db, and it is about to delete the image. For this reason we reference to the most up to date image, and try to "lock" it by committing.

2020-11-20 09:22 UTC, fruttasecca commented on services/orchest-api/app/app/utils.py
> +    return docker_client.images.get(name_or_id).id
I actually wanted the request to fail if a run was trying to use an image that did not exist, I'll handle the request failure better.

2020-11-20 09:28 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_runs.py
> +class ProjectDanglingEnvironmentImages(Resource):
Different levels of granularity. That endpoint will check for all images used in the run if they are dangling, the other tries to remove a single image. I did not want to give to the task in celery the responsibility of querying the more granular endpoint for each used image. It is possible and I would be ok with it if we are trying to trim down end points.

2020-11-20 09:32 UTC, fruttasecca commented
Agree on the fact that the PR is rather immature, the PR was mostly for feedback about what to change and where to trim.

> Lastly, could you also wrap your comments and docstrings at a maximum line length of 72 (for PEP8). It seems like black does not format comments, but currently some are too long to fit on my (split) screen.

Will do!

2020-11-20 16:17 UTC, fruttasecca commented
As the outcome of a discussion, the number of endpoints to take care of dangling images has been trimmed down to 1.
Attempting to deleting potentially dangling images now happens only after an environment build.

2020-11-20 16:40 UTC, yannickperrenet approved these changes
Nice work! Not sure whether the discussion cleared things up or the improved structure of the code did the talking :)

2020-11-20 17:28 UTC, ricklamers commented
So much cleaner! Love how we got it to be smaller and simpler yet still achieve the same underlying goals.

LGTM!

We'll definitely need to do some proper testing (although the race condition sounds tricky to trigger).

2020-11-20 17:32 UTC, ricklamers approved these changes

2020-11-20 17:32 UTC, ricklamers commented on services/orchest-api/app/app/utils.py
> +        in the db yet, and we would end up with  mappings that are
Small typo: were*

2020-11-20 17:34 UTC, merged