add help menu to the client
orchest/orchest pull request #68
Opened 2020-11-23 12:36 UTC by fruttasecca

This PR adds a new menu, "help", to the client, through which the user will be able
to get to the docs, Slack, GitHub and website of Orchest.

![help_menu](https://user-images.githubusercontent.com/19429509/99962633-d494e380-2d90-11eb-8fae-db6410bd33e6.png)

2020-11-23 14:59 UTC, ricklamers requested changes

2020-11-23 14:59 UTC, ricklamers commented on services/orchest-webserver/app/app/config.py
> +    HELP_MENU_CONTENT = {
Refactor the name to be something like "ORCHEST_WEB_URLS" so the generic purpose of these URLs in the webserver config becomes more clear.

2020-11-23 14:59 UTC, ricklamers commented on services/orchest-webserver/app/static/js/views/HelpView.js
> +      website: orchest.config.HELP_MENU_CONTENT.website,
I'd probably prefer the state to be a bit more explicit about the variable referring to a URL. slack_url, readthedocs_url, etc...

2020-11-23 17:20 UTC, yannickperrenet commented
Can we change "https://www.orchest.io" to something like "orchest.io" or "Website", as I now think it is too different from the other items.

I would also like to change the text "doubt or suggestion" to "questions or suggestions". To me "doubts" sound negative.

2020-11-23 18:15 UTC, ricklamers approved these changes
LGTM apart from Yannick's comments! I might have some feedback on how the view is rendered, but if need be we'll address it in a small hotfix commit.

2020-11-23 18:46 UTC, ricklamers commented
> Can we change "https://www.orchest.io" to something like "orchest.io" or "Website", as I now think it is too different from the other items.
> 
> I would also like to change the text "doubt or suggestion" to "questions or suggestions". To me "doubts" sound negative.

I think for consistency we should use www.orchest.io since we use it everywhere over just orchest.io. We can drop the https:// though. Or say "Website".

2020-11-24 08:20 UTC, fruttasecca commented
> > Can we change "https://www.orchest.io" to something like "orchest.io" or "Website", as I now think it is too different from the other items.
> > I would also like to change the text "doubt or suggestion" to "questions or suggestions". To me "doubts" sound negative.
> 
> I think for consistency we should use [www.orchest.io](http://www.orchest.io) since we use it everywhere over just orchest.io. We can drop the https:// though. Or say "Website".

I'll go with Website since it seems more consistent with the rest of the help menu (no wwws).

2020-11-24 08:23 UTC, merged