Better cleanup on removal of pipelines, experiments, projects
orchest/orchest pull request #72
Opened 2020-11-25 12:30 UTC by fruttasecca

This PR is about housekeeping when a deletion of a pipeline, experiment or project is issued. This needs to happen at the file system level, database(s) level and docker environment level.

Upon the deletion of a pipeline, its session is closed, any interactive run is aborted, and the related data is removed from the db.

Upon the deletion of an experiment, the experiment is aborted, removed from disk, related data is removed from the db.

Upon the deletion of a project, any running session, interactive run, experiment, environment build are closed/aborted, related data is removed from disk and the db.

2020-11-25 15:14 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +    def cleanup(project_uuid, environment_uuid):
I am not really a fan of these `staticmethod`s. They are even referenced in different endpoints as well and used outside of the class. I would much rather have them inside of the `utils.py.`

2020-11-25 15:20 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_environment_images.py
> +            Run.stop(run.run_uuid)
Essentially we are invoking (not calling) another endpoint of the API here. Is this "RESTful"?

And on another note, why does the deletion of an environment delete the pipeline runs that use it? Should the environment not at least be locked during (or possibly instantly removed after) a pipeline run? Due to complexity I think locking makes more sense, it just checks whether the environment is used anywhere and states it can therefore not be deleted. If the user however chooses to delete it through the filesystem, then it is up to them.

2020-11-25 15:23 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +        Experiment.stop(experiment)
Should probably be refactor because it uses staticmethods, but also in the refactor this would still apply. I think all the function that do the cleanup should receive a similar object, e.g. always the API parameters instead of sometimes the API parameters and sometimes a DB model.

2020-11-25 15:31 UTC, yannickperrenet commented on services/orchest-api/app/app/models.py
> +        cascade="all, delete",
Not sure whether it would be overkill, but I think it is good to add comments explaining what behavior we are solving by adding these kwargs.

2020-11-25 15:32 UTC, yannickperrenet commented on services/orchest-api/app/app/utils.py
> +        env_uuid (str):
These type annotations in the docstring are not needed since we are already specifying their type in the function definition.

2020-11-25 15:40 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +@api.route("/cleanup/<string:experiment_uuid>")
Why is experiment cleanup not run on deletion of an experiment by default instead of having to call a dedicated endpoint? This question applies to all cleanup that has dedicated endpoints.

2020-11-25 15:44 UTC, yannickperrenet requested changes
I think the general implementation structure needs some work, i.e. usage of endpoints and staticmethods. I would like to minimize the complexity to achieve the cleanup, although I do see that the architecture of the application requires more "complex" cleanup.

2020-11-25 15:56 UTC, fruttasecca commented on services/orchest-api/app/app/models.py
> +        cascade="all, delete",
At line 144 I've added a link to the docs thinking that the first instance of a model using such args was 
at that line, looks like I was wrong. I'll move that up and improve the explanation.

2020-11-25 16:01 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +@api.route("/cleanup/<string:experiment_uuid>")
Because we also support abortion without deletion to allow the state to be read, e.g. by the orchest webserver.

2020-11-25 16:06 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_environment_images.py
> +            Run.stop(run.run_uuid)
>And on another note, why does the deletion of an environment delete the pipeline runs that use it? Should the environment not at least be locked during (or possibly instantly removed after) a pipeline run? Due to complexity I think locking makes more sense, it just checks whether the environment is used anywhere and states it can therefore not be deleted. If the user however chooses to delete it through the filesystem, then it is up to them.

As of now, there is an endpoint to get if an environment is in use, which can be used to tell the user that an environment
deletion will lead to stopping runs/pipelines or to simply reject the user action.

>Due to complexity I think locking makes more sense
I think it might make things slightly more complex because currently its a "fire and forget' behavior, which locking
will not allow.

2020-11-25 16:07 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +        Experiment.stop(experiment)
good point

2020-11-25 16:18 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_environment_builds.py
> +    def cleanup(project_uuid, environment_uuid):
I went with these kind of `staticmethods`s to avoid, essentially, moving a chunk of the actual code of the endpoints
into `utils.py`. 

Since the actual content of these methods is tied to the namespace and the endpoint, an alternative would be
to have, for each `namespace_*.,py`, another file which contains the actual code of the `staticmethods`s, freeing
them from being part of a Resource. I did not do that because I found the code to be more readable (~ less files to traverse) and because I found it handy to have the pattern `Resource.stop` et similia.  

Restructuring from `staticmethod`s to another solution should not be an issue, given that each `staticmethod` is, in a sense, easy to move out of a calss.

2020-11-25 17:14 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_environment_images.py
> +            Run.stop(run.run_uuid)
> As of now, there is an endpoint to get if an environment is in use, which can be used to tell the user that an environment
> deletion will lead to stopping runs/pipelines or to simply reject the user action.

Since it is the webserver that is then responsible for first checking whether it will lead to stopping of runs it is just a shift of responsibility. Either we lock an environment or not, and I am obviously in favor of locking.

> I think it might make things slightly more complex because currently its a "fire and forget' behavior, which locking
> will not allow.

I don't agree. How I see the implementation for locking is also a "fire and forget". Just try to delete the environment, if its in use, then deleting won't work. Once the pipeline run is complete, don't do anything just wait for the user to try to delete the environment again.

2020-11-26 09:45 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_environment_images.py
> +            Run.stop(run.run_uuid)
After our discussion on the locking, we together decided to provide the user with explicit warning messages in case the user wants to delete an environment that is currently being used and that that will stop all runs that depend on it.

2020-11-26 13:55 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +        """Cleanup a pipeline.
Could we change the naming here to "delete" instead of "cleanup"? I feel that the primary action is deleting the pipeline which will then also clean it up.

2020-11-26 14:11 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_pipelines.py
> +        """Cleanup a pipeline.
Will do, and will do the same for other cleanup related functions where applicable

2020-11-26 15:17 UTC, ricklamers commented on services/orchest-api/app/app/models.py
> +    # redundant info since we already have the run_uuid
experiment_uuid is used to update NonInteractiveRunPipelineStep's status.

2020-11-26 15:40 UTC, fruttasecca commented on services/orchest-api/app/app/models.py
> +    # redundant info since we already have the run_uuid
my bad, that was actually meant to say "why we have the exp uuid as part of the primary key"

2020-11-26 15:48 UTC, fruttasecca commented on services/orchest-api/app/app/models.py
> +    # redundant info since we already have the run_uuid
indeed, but it is not needed because of the relationship between `NonInteractiveRun` and `NonInteractiveRunPipelineStep`, I think

2020-11-26 16:35 UTC, yannickperrenet approved these changes

2020-11-26 17:01 UTC, merged