Improve InteractiveRun and Experiment POST endpoints
orchest/orchest pull request #75
Opened 2020-11-27 12:44 UTC by fruttasecca

This PR is a minor refactor of the API endpoints for POSTing interactive runs and experiments. 

It improves logging and storing to db in the case of a failure that made it impossible to start a run (interactive or belonging to an experiment) through the request.

Moreover, it delivers an improved experience in the case a user is actually able to start an interactive run through the GUI when a docker image which is a dependency of the pipeline has been deleted. The GUI will now correctly display a failure and the right button(s), e.g. the run won't be stuck in a permanent pending (and cancelable) state anymore.

2020-11-27 16:42 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
>          return experiment, 201
Should the return code not depend on whether the `experiment_creation_error_messages` list is empty or not?

2020-11-27 16:50 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +                    experiment_creation_error_messages.append(
This comment is actually about the try block. 

Since the set of images will be the same for all pipeline runs of an experiment, I do not think it makes sense to run `lock_environment_images_for_run` inside the for-loop. This also makes this PR easier as we no longer need to maintain a list for `experiment_creation_error_messages` and can instead return here (with an unsuccessful error code). Additionally, the locking of environments should ideally happen before writing to the DB so that the written entries do not have to be updated.

2020-11-27 16:51 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +            db.session.commit()
I think we should reduce the number of times we call `db.session.commit()` to a minimal. This way we don't have to fix the DB entries on errors (if `experiment_creation_error_messages` is not empty) as we simply don't commit to the DB and disregard the changes.

2020-11-27 16:52 UTC, yannickperrenet requested changes
The experiments POST request needs to be refactored.

2020-11-27 16:57 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +            db.session.commit()
I think the entries need to be there, even if failed, so that the client or webserver can make use of that data to inform the user, this is actually a feature, imo.
About the number of commits, not sure how much it can be improved, considering we need the image mapping entries in the db to "lock" an image. I think it's preferable to have all runs of an experiment in the db as FAILED than having only the one needed to lock the required images.

2020-11-27 17:06 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +                    experiment_creation_error_messages.append(
> Since the set of images will be the same for all pipeline runs of an experiment, I do not think it makes sense to run `lock_environment_images_for_run` inside the for-loop. This also makes this PR easier as we no longer need to maintain a list for `experiment_creation_error_messages` and can instead return here (with an unsuccessful error code). 

The experiment POST endpoint needs a bigger refactoring overall, see the TODO around line 55. I did not want to make the PR bigger than it needed to be for its purpose given that we are getting nearer the stable release.

> Additionally, the locking of environments should ideally happen before writing to the DB so that the written entries do not have to be updated.
Locking the environment needs to have entries written to the DB as a requirement, since we are using the DB to know if an environment is or will be used, this is out of scope of the PR.

2020-11-27 17:10 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_experiments.py
>          return experiment, 201
It did, initially. The `orchest-webserver` is acting as a proxy between the `client` and the `orchest-api`, returning error codes such as 500 or 404 will lead to an error. I think this is parallel to the fact that a run needs to have the status of `SUCCESS` to be considered done by the client (and perhaps other moving parts).

2020-11-27 17:20 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
>          return experiment, 201
Then the `orchest-webserver` needs to be updated as well. Possibly also an error code different from 500 or 404 that better covers this case.

2020-11-27 17:25 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +                    experiment_creation_error_messages.append(
In my opinion this should be the time that we do that refactor then. I do not want to keep building on something that is not done well, if that means this PR cannot be included in the stable release then I am fine with that.

2020-11-27 17:29 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +                    experiment_creation_error_messages.append(
I see the PR more as a small refactoring to solve an issue rather than building upon something. I completely agree on the experiments POST endpoint requiring a facelift.

>if that means this PR cannot be included in the stable release then I am fine with that
The issue described in the first comment of the PR should be covered in the stable release, I think.

2020-11-30 12:22 UTC, ricklamers approved these changes

2020-11-30 12:23 UTC, yannickperrenet approved these changes

2020-11-30 12:23 UTC, merged