Named data passing
orchest/orchest pull request #87
Opened 2020-12-10 16:18 UTC by fruttasecca

This PR changes the semantics of the Orchest SDK, in particular, when it comes to data passing.

Outputting data now requires a name. Passing `None` as the name will make the data nameless, while a string will actually become the name of the data. This affects how the data will be later accessed by any child step.

Getting input data (`get_inputs()`) now returns a dictionary instead of a list. This dictionary effectively
acts as a namespace of the received data. Named data is accessed through its key, unnamed data
is aggregated in a list accessed through a reserved key.

The number of public functions in the `transfer` module of the Orchest SDK has been reduced.

2020-12-10 16:40 UTC, yannickperrenet commented on orchest-sdk/python/orchest/__init__.py
> +from orchest.transfer import get_inputs, output, output_to_disk, output_to_memory
I do not see the need to add `output_to_disk` and `output_to_memory` here. I want users to use the `get_inputs` and `output` only, however, if they explicitly want to call the methods then they will have to use the `transfer` module.

2020-12-10 16:45 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +            "'%s' cannot be part of the name of the data" % __METADATA_SEPARATOR__
`.I would like to use f-strings here instead of the old string formatting. Could you also add a `.` to the end of the sentence? These are errors to the users so I want to be strict here.

2020-12-10 16:47 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +    data: Any, name: Union[str, None], serialization: Optional[Serialization] = None
I think using `Optional[str]` over `Union[str, None]` is easier to understand and would follow the same typing as other parts in this module.

2020-12-10 16:50 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +        using :func:`get_inputs`.
The docstring will be formatted incorrectly by sphinx, it has to be like
```python
name: Name of the output data. As a string, it becomes
    the name of the data, when `None`, the data is considered
    nameless. This affects the way the data can be later retrieved
    using :func:`get_inputs`.
```
And please wrap at 72 instead of using arbitrary line wrapping.

2020-12-10 16:54 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +    _check_data_name_validity(name)
Since this function raises errors when checking the validity, these errors should be documented in this method's docstring.

2020-12-10 17:01 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +def _get_output_disk_local(full_path: str, serialization: str) -> Any:
Not sure whether I like the `_local` suffix, because to me it works confusion: "What if it is a network mounted disk? What is different from this function and the one without `_local`?".

In Python we can use a double underscore, giving `__get_output_disk` although this would somewhat (I would argue not entirely) a misuse of the double underscore as a prefix.

2020-12-10 17:05 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +        metadata = __METADATA_SEPARATOR__.join(metadata)
This would yield a line such as:
```
2020-12-10T17:03:08__ORCHEST_METADATA_SEP__PICKLE__ORCHEST_METADATA_SEP__myname
```
which I think is unreadable. So I would rather set the separator to something like `;`.

2020-12-10 17:06 UTC, fruttasecca commented on orchest-sdk/python/orchest/transfer.py
> +def _get_output_disk_local(full_path: str, serialization: str) -> Any:
I think it would indeed be a misuse of the double underscore. I've used `_local` for lack of better names, I am open to suggestions.

2020-12-10 17:07 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +def _get_output_disk(step_uuid: str, serialization: Serialization) -> Any:
This is a wrong merge of master, the type annotation should be `str`. This argument to this function is read from the `HEAD` file and is a string (since it is never parsed to the `Serialization` class afterwards).

2020-12-10 17:08 UTC, fruttasecca commented on orchest-sdk/python/orchest/transfer.py
> +        metadata = __METADATA_SEPARATOR__.join(metadata)
The separator can indeed become easier to read, perhaps we can use something slightly more complex
than `;`, I would prefer not making the `;` character unavailable. `;;;` or something similar could be fine.

2020-12-10 17:08 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +    data: Any, name: Union[str, None], disk_fallback: bool = True
Here Id also like to suggest going with `Optional[str]`

2020-12-10 17:11 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +__METADATA_SEPARATOR__ = "__ORCHEST_METADATA_SEP__"
Should we not put these in the `config.py`?

2020-12-10 17:14 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +            "serialization": serialization,
This `["metadata"]["serialization"]` does not seem to be used anywhere.

2020-12-10 17:17 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +        using :func:`get_inputs`.
This needs more indentation for sphinx. Additionally, for sphinx we need to use double backticks instead of single to get it to be highlighted as code and not italic:
```python
"""
``None``
"""
```

2020-12-10 17:17 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +    _check_data_name_validity(name)
Same applies here regarding the exception raising documentation.

2020-12-10 17:20 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +        # plasma store API
I would like to suggest line wrapping here also and using regular punctuation and capitalization as comments should be written like regular sentences. (Yes, I know I am being overly strict here but I think saying it once is enough and helpful down the line.)

2020-12-10 17:20 UTC, fruttasecca commented on orchest-sdk/python/orchest/transfer.py
> +            "serialization": serialization,
Indeed it is not, as of now. I think it is more consistent since this way it is the complete metadata.

2020-12-10 17:23 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +def _get_output_memory_from_plasma(
I do like this name :+1:

2020-12-10 17:27 UTC, yannickperrenet requested changes
My `mypy` is complaining about a few type annotations, which I think is important to get fixed as these type annotations are in the docs and should be correct (nonetheless). Also I get a warnings when compiling the docs.

2020-12-10 17:38 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +def _get_output_disk_local(full_path: str, serialization: str) -> Any:
Hardest question ever. `_deserialize_output_disk`?

2020-12-10 17:43 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +        metadata = __METADATA_SEPARATOR__.join(metadata)
The only problem with `;` I can think of is that the user can no longer use it in their name when passing the data. However, you do very nicely check whether `__METADATA_SEPARATOR__ in name` so I think its fine to go with `;` (as this is not really a character someone want to include in the name), keeping it more elegant in the `HEAD` file.

2020-12-10 17:48 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +    if len(collisions_dict) > 0:
Here you can just do `if collisions_dict:`

2020-12-10 17:54 UTC, fruttasecca commented on orchest-sdk/python/orchest/transfer.py
> +    if len(collisions_dict) > 0:
Wouldn't this, in a way, be inconsistent with the fact that when checking for `None` we actually do `if X is None`?

2020-12-10 17:55 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +def output(data: Any, name: Union[str, None]) -> None:
`Optional[str]` (just mentioning so we don't miss this one)

2020-12-10 17:58 UTC, fruttasecca commented on orchest-sdk/python/orchest/transfer.py
> +        metadata = __METADATA_SEPARATOR__.join(metadata)
>The only problem with ; I can think of is that the user can no longer use it in their name when passing the data.

Yes, that's what I meant.

>I think its fine to go with `;` or `;`

Did you mean `;;;`?

2020-12-10 18:24 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +        metadata = __METADATA_SEPARATOR__.join(metadata)
I meant `;<space>` but I see the literal space was removed.

2020-12-10 18:26 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +    if len(collisions_dict) > 0:
Checking for `is None` is a special case that should be handled separately. Please refer to https://google.github.io/styleguide/pyguide.html#2144-decision

2020-12-10 18:56 UTC, fruttasecca commented on orchest-sdk/python/orchest/transfer.py
> +        metadata = __METADATA_SEPARATOR__.join(metadata)
`;<space>` it is then

2020-12-11 08:13 UTC, yannickperrenet commented on services/orchest-api/app/tests/input_execution_order/pipeline-7.json
> +            "environment": 0.5
I don't understand why the tests for the orchest-api are changed here? Also, should it not add a new pipeline definition instead of changing an old one?

2020-12-11 08:14 UTC, yannickperrenet requested changes
Everything looks good to me, except for the changes orchest-api tests. It seems to me they are part of other changes and were accidentally included in these commits.

2020-12-11 09:06 UTC, fruttasecca commented on services/orchest-api/app/tests/input_execution_order/pipeline-7.json
> +            "environment": 0.5
The issue with those tests is that they are dependant on race conditions going in a certain way.
The changes to the `transfer` module seem to have made the overall process slightly slower, could be because of the changes to `_resolve_memory`, without that change, those tests would fail so often it was not feasible to make the PR without having failing tests.
Since we decided to not make changes to those tests in this PR, I had to leave in those changes.

2020-12-11 10:08 UTC, fruttasecca commented on services/orchest-api/app/tests/input_execution_order/pipeline-7.json
> +            "environment": 0.5
As discussed, this PR will include a fix for the aforementioned problem.

2020-12-11 16:24 UTC, merged