Move Orchest database backend to postgres
orchest/orchest pull request #91
Opened 2020-12-15 15:51 UTC by fruttasecca

This PR changes the database backend of Orchest from `sqllite` to `postgres`. A new service, `orchest-database`, is launched on start.

The PR affects `orchest-ctl` and services that were persisting their data: the `auth-server`, `orchest-webserver`, `orchest-api`, `celery-worker`.

2020-12-16 08:48 UTC, yannickperrenet commented on services/auth-server/app/app/__init__.py
>          db.create_all()
I think this works fine, but it seems that `create_database` and `db.create_all()` would both try to create the database. Although the latter won't if the first succeeds (because then the db already exists).

In my opinion, the code should be clearer to what exactly is happening here.

2020-12-16 08:53 UTC, yannickperrenet commented on services/orchest-api/app/app/__init__.py
> +            # the db on shutdown
Could you elaborate? I want to make sure I understand it better, because now it seems like a reboot of the `orchest-api` (maybe on failure) could end up deleting its previously issued db changes.

2020-12-16 09:02 UTC, yannickperrenet commented on services/orchest-api/app/app/__init__.py
> +        create_database(CONFIG_CLASS.result_backend_sqlalchemy_uri)
To me the `use_db` kwarg is somewhat confusing if this database creating is put outside of it regardless. Should probably also have a docstring to explain why the kwarg is there in the first place. Seems that its only used for [the celery tasks](https://github.com/orchest/orchest/blob/master/services/orchest-api/app/app/core/tasks.py#L26).

2020-12-16 09:13 UTC, yannickperrenet commented on services/orchest-ctl/app/config.py
> +                "target": "/userdir/.orchest",
The `"source"` should be more precise, e.g. `".orchest/database"`, similarly to how `rabbitmq` is setup. Now the `postgres` container can see the entire `.orchest` directory including `kernels` and `rabbitmq-mnesia`.

Depending on the interaction between the `"target"` , `"PGDATA"` and the `postgres` container this should be as precise as possible.

2020-12-16 09:15 UTC, yannickperrenet commented on services/orchest-ctl/app/cmdline.py
> +        # dependencies among the services? I don't think it's needed.
Its good that you note it here, because we do have a similar dependency between the `jupyter-enterprise-gateway` and the `jupyter-server`. So good to keep in mind that if this keeps reoccurring then we should have a more robust fix.

2020-12-16 09:16 UTC, fruttasecca commented on services/auth-server/app/app/__init__.py
>          db.create_all()
Note that `db.create_all()` will only attempt to create tables, not the database itself. Agree with the fact that I should add some comments in there to better explain what's happening.

2020-12-16 09:19 UTC, yannickperrenet requested changes
The models in the `orchest-api` should, in my opinion, be reworked because we now have one database and therefore the models don't have to be completely isolated anymore.

The schema can be simplified as now there can be inheritance between, e.g. interactive and non-interactive runs. This is a reasonably big schema change and should be done before we ship with the new db implementation (as otherwise we are looking at a difficult migration).

2020-12-16 09:21 UTC, yannickperrenet commented on services/auth-server/app/app/__init__.py
>          db.create_all()
Okay good, because the `db.create_all()` was creating the databases before. Or am I missing something?

2020-12-16 09:24 UTC, fruttasecca commented on services/orchest-api/app/app/__init__.py
> +            # the db on shutdown
Essentially, I have tried to maintain the behaviour where `interactive_*` entities would not really be persisted between different Orchest instances, e.g. restarts. Since those tables are now persisted in the `orchest-database` service and not in a `sqlite` file within the `orchest-api` container, those tables need to be emptied "manually".
I preferred to do this on start so that the `interactive_*` tables would still be inspectable when shutting down Orchest, for easier debugging. 

This might indeed cause those tables to be cleared when the `orchest-api` is running in dev mode and restarts, so clearing only in non dev mode is probably preferable.

2020-12-16 09:28 UTC, fruttasecca commented on services/orchest-api/app/app/__init__.py
> +        create_database(CONFIG_CLASS.result_backend_sqlalchemy_uri)
Indeed.

2020-12-16 09:29 UTC, fruttasecca commented on services/orchest-ctl/app/config.py
> +                "target": "/userdir/.orchest",
Agreed.

2020-12-16 09:29 UTC, fruttasecca commented on services/orchest-ctl/app/cmdline.py
> +        # dependencies among the services? I don't think it's needed.
Yep.

2020-12-16 09:36 UTC, fruttasecca commented
Agreed that this is the right moment (and PR) to change schemas to avoid issues down the line, will do.

2020-12-16 09:47 UTC, fruttasecca commented on services/auth-server/app/app/__init__.py
>          db.create_all()
It did, with `sqlite`. But this is not true for all db flavors. I think it's, actually, only true for `sqlite`, but I can't find the exact specification in the docs.

2020-12-16 10:49 UTC, yannickperrenet commented on services/orchest-api/app/app/__init__.py
> +            # the db on shutdown
And why do we need to clean those entries? Now that we are moving to a different database I would say we can change that behavior as well. I think we should simply store everything.

2020-12-16 10:50 UTC, fruttasecca commented on services/orchest-api/app/app/__init__.py
> +            # the db on shutdown
Fine with me.

2020-12-16 13:55 UTC, yannickperrenet commented on services/orchest-api/app/app/celery_app.py
> +def make_celery(app, create_backend_db=False):
Maybe too much nutpicker but I would propose `use_backed_db` instead of `create_backend_db` since it is not always creating a backend db, the caller of the function just wants to use it.

2020-12-17 11:06 UTC, yannickperrenet commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +        print(non_interactive_run.__dict__)
Could you delete this `print` statement?

2020-12-17 11:07 UTC, fruttasecca commented on services/orchest-api/app/app/apis/namespace_experiments.py
> +        print(non_interactive_run.__dict__)
Yep, totally missed that, my bad.

2020-12-17 11:21 UTC, yannickperrenet approved these changes
Love it!

2020-12-17 12:11 UTC, ricklamers commented on services/orchest-api/app/app/models.py
> +        # Essentially, the specifed behaviour in the FK column
specified*

2020-12-17 12:11 UTC, ricklamers commented on services/orchest-api/app/app/models.py
> +    status = db.Column(db.String(15), unique=False, nullable=True)
Wasn't this supposed to be more than 15?

2020-12-17 14:03 UTC, ricklamers approved these changes

2020-12-17 14:46 UTC, yannickperrenet approved these changes

2020-12-18 09:41 UTC, yannickperrenet commented on services/orchest-api/app/app/__init__.py
> +            if os.system("mkdir /tmp/interactive_cleanup_done > /dev/null 2>&1") == 0:
Can it not be the `os.mkdir` function instead of issues an os command?

2020-12-18 09:49 UTC, fruttasecca commented on services/orchest-api/app/app/__init__.py
> +            if os.system("mkdir /tmp/interactive_cleanup_done > /dev/null 2>&1") == 0:
Will do

2020-12-18 10:04 UTC, merged