Enable schema migrations
orchest/orchest pull request #98
Opened 2020-12-18 15:27 UTC by fruttasecca

This PR enables the management of schema migrations, so that, from now on, outdated databases will be brought to an up to date schema automatically.

From a developer perspective, managing migrations will require running `scripts/migration_manager.sh` to issue migration commands. Generally speaking, the only needed command will be the one to generate new revision files:
`scripts/migration_manager.sh <service-name> migrate`

2020-12-18 15:44 UTC, ricklamers reviewed
The env.py, script.py.mako, and migration_manager.py seem to be duplicated for each service. Can we be smarter about this?

2020-12-18 15:44 UTC, ricklamers commented on scripts/migration_manager.sh
> +if [ $code -eq 0 ]; then
I guess the command will output its errors on the terminal that invoked this bash file, hence you're ignoring the != 0 exit code case?

2020-12-18 15:44 UTC, ricklamers commented on services/orchest-webserver/app/app/models.py
> +        # plugin, leaving it as an ORM-only default
What will the actual default value in the DB be in this case?

2020-12-18 15:45 UTC, ricklamers commented
Overall I think this is an _excellent_ PR that will add lots of value to users by not breaking the database state when we have to make schema changes!

2020-12-18 15:52 UTC, fruttasecca commented on services/orchest-webserver/app/app/models.py
> +        # plugin, leaving it as an ORM-only default
No default value at the database schema level. Since it is non nullable, it simply will not allow to input records with no uuids, e.g. (note the missing `uuid` column):
`insert into environments (name, project_uuid, language, setup_script, base_image, gpu_support) values ('name', 'proj', 'english', '1', 'my_image', '0');`
Will result in a error. The default (generating a uuid) is of course still present at the ORM level. It makes for a less strict schema but installing a plugin did not seem like a better trade-off.

2020-12-18 15:53 UTC, fruttasecca commented on scripts/migration_manager.sh
> +if [ $code -eq 0 ]; then
Yes, that's the case.

2020-12-18 16:15 UTC, fruttasecca commented
> The env.py, script.py.mako, and migration_manager.py seem to be duplicated for each service. Can we be smarter about this?

`migration_manager.py` contains a minimal amount of lines of code and cannot be exactly the same for each service. Note, for example, that the one in the `orchest-webserver` directory is slightly different because of what `init_app_` is returning. I see it as a sibling of `main.py`.

The `migrations` directory of each service that requires migrations needs to be there for `flask-migrate`/`alembic`. When issuing a `migrate` command you actually pass the `migrations` directory, not the `revisions` one. It's going to pick up what's in there, like `env.py`, and save to `revisions`.

We might be able to avoid duplication by having a single copy of those files in the repo and `COPY`ing them in the dockerfile, but that would mean not having them in place in `dev` mode I believe, and possibly not being able to customize them for each service (not that I think we are going to need to do that).

2020-12-18 18:47 UTC, ricklamers commented on services/orchest-api/app/app/__init__.py
> +        # necessary for migration related stuff
I'd prefer not to use the word 'stuff' >.<
Can we just say `# necessary for migration`

2020-12-18 18:50 UTC, ricklamers commented on services/auth-server/app/app/__init__.py
> +    # necessary for migration related stuff
Same as before

2020-12-18 18:50 UTC, ricklamers commented on services/orchest-webserver/app/app/__init__.py
> +    # necessary for migration related stuff
Same as before

2020-12-18 18:51 UTC, ricklamers commented on services/orchest-webserver/app/app/__init__.py
> +    # necessary for migration related stuff
https://user-images.githubusercontent.com/1309307/102649977-6f9f9400-416a-11eb-81a1-20830c2612aa.mov

2020-12-19 14:22 UTC, yannickperrenet commented on services/auth-server/app/app/connections.py
> +metadata = MetaData(naming_convention=config.database_naming_convention)
For consistency and explicitness that the `config` is actually the internal library config.
```suggestion
from _orchest.internals import config as _config

# this will make it so that constraints and indexes follow a certain
# naming pattern
metadata = MetaData(naming_convention=_config.database_naming_convention)
```

2020-12-19 14:29 UTC, yannickperrenet commented on services/auth-server/Dockerfile
> +COPY ./lib /orchest/lib
The javascript library is already copied in in a later step and should not invalidate the cache for installing the Python requirements.

```suggestion
COPY ./lib/python /orchest/lib/python
```

2020-12-19 14:35 UTC, yannickperrenet commented on services/auth-server/app/migration_manager.py
> +    manager.run()
The `Manager` seems to be started when running the `scripts/migration_manager.sh` but it is never shut down? Is that on purpose and if so could you explain why?

I think it can be beneficial to not shut down the manager afterwards, but want to better understand your reasoning behind it (if it is indeed still running).

2020-12-19 14:38 UTC, yannickperrenet commented on services/orchest-api/app/app/connections.py
> +from _orchest.internals import config
Would like to refer to the same suggestion for the auth-server adding `as _config`.

2020-12-19 14:39 UTC, yannickperrenet commented on services/orchest-webserver/app/app/connections.py
> +db = SQLAlchemy(metadata=metadata)
For consistency and explicitness that the `config` is actually the internal library config.
```suggestion
from _orchest.internals import config as _config

# this will make it so that constraints and indexes follow a certain
# naming pattern
metadata = MetaData(naming_convention=_config.database_naming_convention)
```

2020-12-19 14:44 UTC, yannickperrenet requested changes
The migrations are a great addition, improving the lives of the ("updating") user.

I only had a few minor suggestions and would like to first better understand the choice behind the `Manager` that seems to keep running.

2020-12-19 16:29 UTC, ricklamers commented on services/auth-server/app/migration_manager.py
> +    manager.run()
Doesn’t this script only run when you perform the migration?

2020-12-21 09:06 UTC, fruttasecca commented on services/auth-server/app/migration_manager.py
> +    manager.run()
The script does indeed only run when performing a migration, it's pretty much just parsing the arguments and passing them to the related function.
https://github.com/smurfix/flask-script/blob/master/flask_script/__init__.py#L396

2020-12-21 09:14 UTC, yannickperrenet approved these changes

2020-12-21 09:14 UTC, merged