Feature improve SDK robustness
orchest/orchest pull request #99
Opened 2020-12-21 13:43 UTC by fruttasecca

This PR aims to improve the robustness of the Orchest SDK. It adds some `try/except` blocks and some customs Exceptions so that errors are more explicit.

2020-12-21 17:28 UTC, ricklamers commented
LGTM!

2020-12-21 17:28 UTC, ricklamers approved these changes

2020-12-21 20:19 UTC, yannickperrenet commented on orchest-sdk/python/orchest/errors.py
> +    pass
To me these classes are a bit overkill. I would not go more granular than `DeserializationError` or simply `SerializationError` (and also removing `DeserializationError`).

2020-12-21 20:20 UTC, yannickperrenet commented on orchest-sdk/python/orchest/errors.py
>      """Data has an invalid name"""
```suggestion
"""Data has an invalid name."""
```

2020-12-21 20:24 UTC, yannickperrenet commented on orchest-sdk/python/orchest/errors.py
> +    """
```suggestion
    """Metadata is invalid."""
```
Not sure the second paragraph of the error has an added benefit since when using the `InvalidMetaDataError` the message already explain why the metadata is valid, e.g. it is missing the separator.

2020-12-21 20:24 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
>  )
Now that we are importing so many error it would make more sense if we do `from orchest import errors` and use it like `errors.OrchestNetworkError` instead.

2020-12-21 20:37 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +            the data was output.
This indentation level can be reduced.
```suggestion
        A tuple of 3 strings. The first is the timestamp of when the
        data related to the metadata was produced (utc, ISO format).
        The second string is the type of serialization used (See the
        Serialization enum). The third string is the name with which the
        data was output.
```

2020-12-21 20:41 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +def _interpret_metadata(metadata: str) -> Tuple[str, str, str]:
Even though I love this function, I am not sure I want output messages such as: "Metadata has an invalid timestamp". I don't see why a user should know this, the user never even wrote it in the first place and it is therefore not a helpful message to the user. Even though this is indeed the cause, we should give a different message to the user, e.g.: "Metadata is invalid. The project directory might have cached the old metadata when upgrading to the new version of Orchest."

2020-12-21 20:42 UTC, yannickperrenet commented on orchest-sdk/python/orchest/transfer.py
> +                f"Metadata {metadata} has an" f"invalid timestamp ({timestamp})."
```suggestion
                f"Metadata {metadata} has an invalid timestamp ({timestamp})."
```

2020-12-21 20:48 UTC, yannickperrenet requested changes
Overall I do really like the idea of adding robustness. However, I think to the user many of the error messages are not "helping". Yes they state exactly what the problem is, but the user does not know how to fix it and did not directly cause the issue, we did.

2020-12-21 20:55 UTC, ricklamers commented
> Overall I do really like the idea of adding robustness. However, I think to the user many of the error messages are not "helping". Yes they state exactly what the problem is, but the user does not know how to fix it and did not directly cause the issue, we did.

I think it's good to keep in mind that even though the user might not fully understand all error messages - often it can be helpful if the user "just wants to fix it" that they know in which direction to look. Obviously many of these errors _should_ never be triggered at all. But when the ball is dropped, at least the user is empowered to find a solution.

2020-12-22 07:01 UTC, yannickperrenet commented
> I think it's good to keep in mind that even though the user might not fully understand all error messages - often it can be helpful if the user "just wants to fix it" that they know in which direction to look. 

I strongly disagree! The user has no influence over the metadata and therefore has no idea where to look (let alone how to fix, the user cannot even fix it in some of the cases). We need to tell the user where to look. 

For example (like I proposed in one of the other comments), instead of "Metadata has an invalid timestamp" we can do "Metadata is invalid. The project directory might have cached the old metadata when upgrading to the new version of Orchest." Although even better might even be: "Metadata is invalid, it has an invalid timestamp. The issue might be caused due to cached metadata when upgrading to the new version of Orchest, try to delete the `.orchest/pipelines` directory inside your pipeline directory."

I do think an error message should include what went wrong (so adding the "timestamp" in the example makes sense), but it should also steer the user in the right direction to fix it.

2020-12-22 08:41 UTC, fruttasecca commented on orchest-sdk/python/orchest/errors.py
> +    """
Agree

2020-12-22 08:47 UTC, ricklamers commented
I think we actually agree then. You just want to also add more detailed messages with the errors, which I think is a good idea.

2020-12-22 08:48 UTC, fruttasecca commented
> I strongly disagree! The user has no influence over the metadata and therefore has no idea where to look (let alone how to fix, the user cannot even fix it in some of the cases). We need to tell the user where to look.

I agree that the messages should be improved to steer the user towards fixing its issue.  I'll improve the messages to contain both the cause and a suggestion to fix. From my POV, the cause is there so that we can quickly find the reason an occurrence that should never happen has taken place.

2020-12-22 08:49 UTC, fruttasecca commented on orchest-sdk/python/orchest/transfer.py
>  )
Will do.

2020-12-22 08:52 UTC, fruttasecca commented on orchest-sdk/python/orchest/errors.py
> +    pass
I can do without having both `Disk/Memory DeserializationError`, but I think that at least `DeserializationError` should stay.

2020-12-22 10:50 UTC, yannickperrenet commented on orchest-sdk/python/orchest/error.py
> +    """Error when an object cannot be serialized."""
Should probably be "deserialized"

2020-12-22 10:53 UTC, yannickperrenet commented on orchest-sdk/python/orchest/error.py
> +        super().__init__(msg, *args, **kwargs)
Love it! :100:

2020-12-22 11:24 UTC, fruttasecca commented on orchest-sdk/python/orchest/error.py
> +    """Error when an object cannot be serialized."""
Indeed.

2020-12-22 11:46 UTC, yannickperrenet approved these changes

2020-12-22 11:54 UTC, merged